---
boundary: '03'
appName: api-gateway
destinationNamespace: platform-controlplane
isPlatformOwned: 'true'
repoURL: ''
targetRevision: ''
path: manifests/hub-core-services/api-gateway
chart: ''
directoryRecurse: ''
directoryInclude: ''
helmValues: ''
helmReleaseName: ''
ignoreDifferencesNamespace: ''
extraManifestsPath: ''
