---
boundary: '03'
appName: hub-operator
destinationNamespace: platform-ops
isPlatformOwned: 'true'
repoURL: ''
targetRevision: ''
path: operators/hub-operator/config/default
chart: ''
directoryRecurse: ''
directoryInclude: ''
helmValues: ''
helmReleaseName: ''
ignoreDifferencesNamespace: ''
extraManifestsPath: ''
