---
boundary: '03'
appName: platform-tenant-platform
destinationNamespace: default
isPlatformOwned: 'true'
repoURL: ''
targetRevision: ''
path: manifests/hub-core-services/crossplane/tenant-platform
chart: ''
directoryRecurse: 'true'
directoryInclude: ''
helmValues: ''
helmReleaseName: ''
ignoreDifferencesNamespace: ''
extraManifestsPath: ''
