---
boundary: '03'
appName: platform-infisical
destinationNamespace: platform-security
isPlatformOwned: 'true'
repoURL: ''
targetRevision: ''
path: manifests/hub-core-services/infisical
chart: ''
directoryRecurse: ''
directoryInclude: ''
helmValues: ''
helmReleaseName: ''
ignoreDifferencesNamespace: ''
extraManifestsPath: ''
