---
boundary: '03'
appName: platform-dns
destinationNamespace: kube-system
isPlatformOwned: 'true'
repoURL: ''
targetRevision: ''
path: manifests/hub-core-services/dns
chart: ''
directoryRecurse: ''
directoryInclude: ''
helmValues: ''
helmReleaseName: ''
ignoreDifferencesNamespace: ''
extraManifestsPath: ''
