---
boundary: '03'
appName: platform-cert-manager
destinationNamespace: cert-manager
isPlatformOwned: 'true'
repoURL: ''
targetRevision: ''
path: manifests/hub-core-services/cert-manager
chart: ''
directoryRecurse: ''
directoryInclude: ''
helmValues: ''
helmReleaseName: ''
ignoreDifferencesNamespace: ''
extraManifestsPath: ''
