apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kratos-selfservice-ui
  namespace: platform-ops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/soloz-io/zero-ops
    targetRevision: HEAD
    path: manifests/platform-identity/kratos-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-identity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
