apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ory-keto
  namespace: platform-ops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: https://k8s.ory.sh/helm/charts
      chart: keto
      targetRevision: "0.60.1"
      helm:
        valueFiles:
          - $values/manifests/hub-core-services/identity/ory-keto/values.yaml
    - repoURL: https://github.com/soloz-io/zero-ops
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/soloz-io/zero-ops
      targetRevision: HEAD
      path: manifests/hub-core-services/identity/ory-keto
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-identity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 15
      backoff:
        duration: 30s
        maxDuration: 10m
