apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ory-keto
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://k8s.ory.sh/helm/charts
    targetRevision: 0.45.4
    chart: keto
    helm:
      valueFiles:
        - values.yaml
      values: |
        {{- readFile "manifests/platform-identity/ory-keto/values.yaml" | nindent 8 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: ory-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
