apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../_shared
  - k8s/hetzner-credentials-es.yaml
  - k8s/tailscale-psk-es.yaml
  - k8s/cilium-addon-flatcar.yaml
  - k8s/csi-addon-flatcar.yaml
  - k8s/home-worker-integration.yaml
  - k8s/spokepool-hybrid-flatcar-composition.yaml
