apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: platform@zero-ops.io
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        webhook:
          groupName: hetzner.cert-mananger-webhook.noshoes.xyz
          solverName: hetzner
          config:
            secretName: hetzner-dns
            zoneName: zero-ops.io
            apiUrl: https://dns.hetzner.com/api/v1
