apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

images:
- digest: sha256:956056f79d5477bc4be742d6650ab41b0fc49fac676aaf33cd8afe0ca23cc878
  name: controller
  newName: ghcr.io/soloz-io/spoke-identity-operator
