apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

images:
- digest: sha256:65ce1bca1550d5e8a8e0f535f0c65c2a811daa160a316b2914396c687054ee84
  name: controller
  newName: ghcr.io/soloz-io/spoke-identity-operator
