apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

images:
- digest: sha256:a9c20a606fcd9711c7c2ef540bcc2f456c2bcaafb3a995a266dbacff483c05bc
  name: controller
  newName: ghcr.io/soloz-io/spoke-identity-operator
