resources:
- manager.yaml

images:
- digest: sha256:1294907201cc10a9f114abec992a9b5514252e39b9d0a49e277ef33ae348443a
  name: controller
  newName: ghcr.io/soloz-io/zero-ops/hub-operator
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
