resources:
- manager.yaml
- provider-registry.yaml

images:
- digest: sha256:65e9a0f9e484112628915906fc4750ddbdcf7750bfcdfbb42e157cedde9cc3c3
  name: controller
  newName: ghcr.io/soloz-io/zero-ops/hub-operator
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
