apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: control-plane-db-credentials
  namespace: platform-data
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: infisical-backend
    kind: ClusterSecretStore

  target:
    name: control-plane-db-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        url: "postgresql://{{ .username }}:{{ .password }}@platform-db-rw.platform-data.svc.cluster.local:5432/control_plane?sslmode=require"

  data:
    - secretKey: username
      remoteRef:
        key: hub-control-plane-db-username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: hub-control-plane-db-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
