#!/usr/bin/env bash
# scripts/hybrid/join-home-workers.sh
# ─────────────────────────────────────────────────────────────────────────────
# Mac-side driver for hybrid home-worker (WSL2) join (ADR-046 §WS3/F).
#
# Codifies the previously-manual join so it cannot silently break again:
#   1. Reads home-lab.env (node registry + hub kubeconfig path).
#   2. For each node: verifies SSH + Tailscale are up, pushes the hub
#      kubeconfig and join tooling onto the node, then runs the join.
#   3. Installs a systemd oneshot+timer on the node so membership is
#      re-established automatically on boot / network return / periodic ticks.
#
# Idempotent: safe to re-run any time. Already-joined nodes are verified and
# re-labeled, not re-joined.
#
# Usage:
#   ./join-home-workers.sh [--node 1] [--env ./home-lab.env]
#     --node N   only join node index N (1-based). Default: all nodes.
#     --env F    path to home-lab.env. Default: scripts/hybrid/home-lab.env
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

ENV_FILE="$(dirname "$0")/home-lab.env"
ONLY_NODE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --node) ONLY_NODE="$2"; shift 2 ;;
    --env)  ENV_FILE="$2"; shift 2 ;;
    *) echo "ERROR: unknown arg $1" >&2; exit 1 ;;
  esac
done

if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: $ENV_FILE not found. Copy home-lab.env.example → home-lab.env." >&2
  exit 1
fi
# shellcheck source=/dev/null
source "$ENV_FILE"

if [[ ! -f "$HUB_KUBECONFIG" ]]; then
  echo "ERROR: HUB_KUBECONFIG not found: $HUB_KUBECONFIG" >&2
  echo "       Check home-lab.env — the hub kubeconfig must exist on the Mac." >&2
  exit 1
fi

HERE="$(cd "$(dirname "$0")" && pwd)"
JOIN_SCRIPT="$HERE/home-worker-join.sh"
REMOTE_DIR="/etc/hybrid"
REMOTE_KUBECONFIG="$REMOTE_DIR/hub.kubeconfig"
REMOTE_ENV="$REMOTE_DIR/home-lab.env"

echo "=== Hybrid home-worker join driver ==="
echo "    Spoke:   ${HYBRID_SPOKE_NAME}"
echo "    Tailnet: ${TAILNET_NAME}"
echo "    Hub kc:  ${HUB_KUBECONFIG}"
echo ""

NODE_IDX=0
while IFS='|' read -r HOSTNAME SSH_TARGET WSL_DISTRO TAILNET_HOST BOX_TAG; do
  [[ -z "$HOSTNAME" ]] && continue
  NODE_IDX=$((NODE_IDX + 1))

  if [[ -n "$ONLY_NODE" && "$NODE_IDX" != "$ONLY_NODE" ]]; then
    continue
  fi

  echo "── node ${NODE_IDX}: ${HOSTNAME} (${BOX_TAG}) ─────────────────"
  echo "    SSH: ${SSH_TARGET}  WSL: ${WSL_DISTRO}  Tailnet: ${TAILNET_HOST}"

  # 1. SSH must work (use a PowerShell-native command; default shell on the
  #    Windows host is PowerShell, where `true` is not a valid command)
  if ! ssh -o BatchMode=yes -o ConnectTimeout=6 -o StrictHostKeyChecking=no \
        "${SSH_TARGET}" "echo ok" 2>/dev/null; then
    echo "    ✗ SSH to ${SSH_TARGET} failed — skipping (node unreachable)." >&2
    continue
  fi

  # WSL entry point (Windows default shell is PowerShell; always invoke bash in WSL).
  WSL="wsl -d ${WSL_DISTRO} -u root -e bash -lc"

  # 2. Tailscale must be up + authenticated inside WSL. tailscaled can flap
  #    (transient "NoState" during restart), so retry for up to ~60s.
  echo "    → waiting for Tailscale in ${WSL_DISTRO}..."
  TS_OK=0
  for _ in $(seq 1 12); do
    if ssh -o BatchMode=yes -o ConnectTimeout=6 -o StrictHostKeyChecking=no \
          "${SSH_TARGET}" "${WSL} 'tailscale status --peers=false >/dev/null 2>&1'"; then
      TS_OK=1
      break
    fi
    sleep 5
  done
  if [[ "$TS_OK" != "1" ]]; then
    echo "    ✗ Tailscale not up in ${WSL_DISTRO}. Run 'sudo tailscale up' on the node first." >&2
    continue
  fi
  echo "    ✓ SSH + Tailscale"

  # 3. Push hub kubeconfig (base64 to dodge PowerShell quoting)
  echo "    → pushing hub kubeconfig → ${REMOTE_KUBECONFIG}"
  KCB64="$(base64 < "$HUB_KUBECONFIG" | tr -d '\n')"
  ssh -o BatchMode=yes -o ConnectTimeout=6 -o StrictHostKeyChecking=no \
    "${SSH_TARGET}" "${WSL} 'mkdir -p ${REMOTE_DIR} && echo ${KCB64} | base64 -d > ${REMOTE_KUBECONFIG} && chmod 600 ${REMOTE_KUBECONFIG}'"

  # 4. Push the join script + env
  echo "    → pushing join tooling → ${REMOTE_DIR}"
  SB64="$(base64 < "$JOIN_SCRIPT" | tr -d '\n')"
  ssh -o BatchMode=yes -o ConnectTimeout=6 -o StrictHostKeyChecking=no \
    "${SSH_TARGET}" "${WSL} 'echo ${SB64} | base64 -d > ${REMOTE_DIR}/home-worker-join.sh && chmod 700 ${REMOTE_DIR}/home-worker-join.sh'"

  # Node-local env: same registry, but HUB_KUBECONFIG is the pushed copy.
  {
    echo "# generated by join-home-workers.sh on $(date -u +%FT%TZ)"
    echo "HOME_WORKER_NODES=\"${HOME_WORKER_NODES}\""
    echo "TAILNET_NAME=\"${TAILNET_NAME}\""
    echo "HYBRID_SPOKE_NAME=\"${HYBRID_SPOKE_NAME}\""
    echo "HUB_KUBECONFIG=\"${REMOTE_KUBECONFIG}\""
    echo "NODE_INDEX=\"${NODE_IDX}\""
  } > /tmp/hybrid-home-lab.$$.env
  EB64="$(base64 < /tmp/hybrid-home-lab.$$.env | tr -d '\n')"
  rm -f /tmp/hybrid-home-lab.$$.env
  ssh -o BatchMode=yes -o ConnectTimeout=6 -o StrictHostKeyChecking=no \
    "${SSH_TARGET}" "${WSL} 'echo ${EB64} | base64 -d > ${REMOTE_ENV}'"

  # 5. Install self-healing systemd unit + timer (oneshot join on boot/network,
  #    plus periodic re-verify every 10 min). Already-joined → join exits 0.
  echo "    → installing systemd auto-join unit + timer"
  UNIT="hybrid-home-worker-join"
  SVC="/etc/systemd/system/${UNIT}.service"
  TIMER="/etc/systemd/system/${UNIT}.timer"
  cat > /tmp/hybrid-join.$$.service <<EOF
[Unit]
Description=Hybrid home worker auto-join (node ${NODE_IDX}, ${HOSTNAME})
Wants=network-online.target tailscaled.service
After=network-online.target tailscaled.service
ConditionPathExists=${REMOTE_KUBECONFIG}

[Service]
Type=oneshot
ExecStart=${REMOTE_DIR}/home-worker-join.sh ${NODE_IDX} --env ${REMOTE_ENV}
TimeoutStartSec=300
EOF
  cat > /tmp/hybrid-join.$$.timer <<EOF
[Unit]
Description=Periodic hybrid home worker membership check (node ${NODE_IDX})

[Timer]
OnBootSec=1min
OnUnitActiveSec=10min
Unit=${UNIT}.service

[Install]
WantedBy=timers.target
EOF
  SVCB64="$(base64 < /tmp/hybrid-join.$$.service | tr -d '\n')"
  TIMERB64="$(base64 < /tmp/hybrid-join.$$.timer | tr -d '\n')"
  rm -f /tmp/hybrid-join.$$.service /tmp/hybrid-join.$$.timer
  ssh -o BatchMode=yes -o ConnectTimeout=6 -o StrictHostKeyChecking=no \
    "${SSH_TARGET}" "${WSL} 'echo ${SVCB64} | base64 -d > ${SVC} && echo ${TIMERB64} | base64 -d > ${TIMER} && systemctl daemon-reload && systemctl enable --now ${UNIT}.timer && systemctl restart ${UNIT}.service'"

  # 6. Run the join now and report result
  echo "    → running join on node ${NODE_IDX}"
  if ssh -o BatchMode=yes -o ConnectTimeout=6 -o StrictHostKeyChecking=no \
        "${SSH_TARGET}" "${WSL} '${REMOTE_DIR}/home-worker-join.sh ${NODE_IDX} --env ${REMOTE_ENV}'"; then
    echo "    ✓ ${HOSTNAME} join completed (or already member)"
  else
    echo "    ✗ ${HOSTNAME} join returned non-zero — see node logs above." >&2
  fi
  echo ""
done <<< "$HOME_WORKER_NODES"

echo "=== Done ==="
echo "    Verify: kubectl --kubeconfig=\$HUB_KUBECONFIG get nodes"
