apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-ops

resources:
  - namespace.yaml
  - manager.yaml
  - network-policy.yaml

images:
- digest: sha256:515232934fb9fdcbe88d3e879a30747f5f32ed650bb67eb9ab0169fbd763fd29
  name: controller
  newName: ghcr.io/soloz-io/zero-ops/kube-sbt-api

labels:
- pairs:
    app.kubernetes.io/component: metering-api
    app.kubernetes.io/name: kube-sbt-api
    app.kubernetes.io/part-of: kube-sbt
