apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-ops

resources:
- manager.yaml
- network-policy.yaml
- identity-credentials-es.yaml

images:
- digest: sha256:def4c256279280fa3d4a4da1d276368d068b31cd51d59ab2c3c36ce5618e8bcf
  name: controller
  newName: ghcr.io/soloz-io/zero-ops/kube-sbt-api

labels:
- pairs:
    app.kubernetes.io/component: metering-api
    app.kubernetes.io/name: kube-sbt-api
    app.kubernetes.io/part-of: kube-sbt
