apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mcp-server
  namespace: hub-platform-ops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/soloz-io/zero-ops
    targetRevision: HEAD
    path: manifests/platform-core-services/api-gateway/mcp-server
  destination:
    server: https://kubernetes.default.svc
    namespace: hub-platform-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
