appName: grafana-alloy
destinationNamespace: platform-observability
isPlatformOwned: false
targetRevision: main
repoURL: https://github.com/soloz-io/zero-ops.git
path: manifests/hub-core-services/grafana-alloy
syncOptions:
- CreateNamespace=true
retryLimit: 5
retryDuration: 5s
retryMaxDuration: 3m
