appName: platform-infisical
destinationNamespace: platform-security
isPlatformOwned: true
repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
chart: infisical-standalone
syncOptions:
- CreateNamespace=true
retryLimit: 15
retryDuration: 30s
retryMaxDuration: 10m
sources:
- repoURL: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
  chart: infisical-standalone
  targetRevision: 1.7.5
- repoURL: https://github.com/soloz-io/zero-ops
  targetRevision: HEAD
  ref: values
