appName: victoria-metrics-cluster
destinationNamespace: platform-observability
isPlatformOwned: false
targetRevision: 0.37.0
repoURL: https://victoriametrics.github.io/helm-charts
chart: victoria-metrics-cluster
helmValues: "vmselect:\n  replicaCount: 1\n  resources:\n    requests:\n      cpu:\
  \ 250m\n      memory: 256Mi\n    limits:\n      cpu: 1000m\n      memory: 2Gi\n\
  vminsert:\n  replicaCount: 1\n  resources:\n    requests:\n      cpu: 250m\n   \
  \   memory: 256Mi\n    limits:\n      cpu: 1000m\n      memory: 2Gi\nvmstorage:\n\
  \  replicaCount: 1\n  persistentVolume:\n    enabled: true\n    size: 50Gi\n  resources:\n\
  \    requests:\n      cpu: 500m\n      memory: 512Mi\n    limits:\n      cpu: 2000m\n\
  \      memory: 4Gi\nretentionPeriod: 30d\n"
syncOptions:
- CreateNamespace=true
retryLimit: 5
retryDuration: 5s
retryMaxDuration: 3m
