appName: hub-operator
destinationNamespace: platform-ops
isPlatformOwned: true
repoURL: https://github.com/soloz-io/zero-ops
path: operators/hub-operator/config/default
syncOptions:
- CreateNamespace=true
- ServerSideApply=true
retryLimit: 15
retryDuration: 30s
retryMaxDuration: 10m
