appName: platform-capi2argo
destinationNamespace: platform-ops
isPlatformOwned: true
repoURL: https://github.com/soloz-io/zero-ops
path: manifests/hub-core-services/capi2argo
syncOptions:
- CreateNamespace=true
- ServerSideApply=true
retryLimit: 5
retryDuration: 5s
retryMaxDuration: 3m
