appName: hub-environment
destinationNamespace: platform-ops
isPlatformOwned: true
repoURL: https://github.com/soloz-io/zero-ops
path: manifests/hub-core-services/hub-environment
syncOptions:
- CreateNamespace=true
- ServerSideApply=true
retryLimit: 15
retryDuration: 30s
retryMaxDuration: 10m
