appName: platform-spire
destinationNamespace: platform-security
isPlatformOwned: true
repoURL: https://github.com/soloz-io/zero-ops
path: manifests/hub-core-services/spire
syncOptions:
- CreateNamespace=true
retryLimit: 5
retryDuration: 5s
retryMaxDuration: 3m
