appName: victoria-metrics-operator
destinationNamespace: platform-observability
isPlatformOwned: false
targetRevision: 0.59.3
repoURL: https://victoriametrics.github.io/helm-charts
chart: victoria-metrics-operator
syncOptions:
- CreateNamespace=true
retryLimit: 5
retryDuration: 5s
retryMaxDuration: 3m
