appName: platform-external-dns-secrets
destinationNamespace: platform-edge
isPlatformOwned: false
targetRevision: main
repoURL: https://github.com/soloz-io/zero-ops
path: manifests/hub-core-services/external-dns
syncOptions:
- CreateNamespace=true
retryLimit: 15
retryDuration: 30s
retryMaxDuration: 10m
