appName: prometheus-operator
destinationNamespace: platform-observability
isPlatformOwned: false
targetRevision: 82.15.0
repoURL: https://prometheus-community.github.io/helm-charts
chart: kube-prometheus-stack
helmValues: "prometheus:\n  enabled: false\nalertmanager:\n  enabled: false\ngrafana:\n\
  \  enabled: false\nprometheusOperator:\n  enabled: true\nkubeStateMetrics:\n  enabled:\
  \ false\nnodeExporter:\n  enabled: false\n"
syncOptions:
- CreateNamespace=true
- ServerSideApply=true
retryLimit: 5
retryDuration: 5s
retryMaxDuration: 3m
