appName: platform-spoke-pools
destinationNamespace: platform-ops
isPlatformOwned: true
repoURL: https://github.com/soloz-io/zero-ops
path: manifests/spoke/spoke-pools
directoryRecurse: true
syncWave: '10'
syncOptions:
- CreateNamespace=true
retryLimit: 5
retryDuration: 30s
retryMaxDuration: 10m
