appName: platform-tenant-platform
destinationNamespace: default
isPlatformOwned: true
repoURL: https://github.com/soloz-io/zero-ops
path: manifests/hub-core-services/crossplane/tenant-platform
directoryRecurse: true
syncWave: '5'
syncOptions:
- CreateNamespace=true
- ServerSideApply=true
retryLimit: 5
retryDuration: 5s
retryMaxDuration: 3m
ignoreDifferences:
- group: kubernetes.crossplane.io
  kind: Object
  jqPathExpressions:
  - .metadata.annotations["crossplane.io/external-name"]
  - .spec.readiness
