apiVersion: v1
kind: ConfigMap
metadata:
  name: agentgateway-config
  namespace: api-gateway
data:
  config.yaml: |
    binds:
    - port: 3000
      listeners:
      - routes:
        - matches:
          - path:
              exact: /health
          policies:
            directResponse:
              status: 200
              body: "OK"
        - backends:
          - host: auth-proxy.identity-services.svc.cluster.local:8080
          matches:
          - path:
              exact: /.well-known/oauth-authorization-server/mcp
          - path:
              exact: /.well-known/oauth-authorization-server
        - backends:
          - mcp:
              targets:
              - name: demo-echo
                mcp:
                  host: http://demo-echo.api-gateway.svc.cluster.local:8080/mcp
          matches:
          - path:
              pathPrefix: /mcp
          - path:
              exact: /.well-known/oauth-protected-resource/mcp
          - path:
              exact: /.well-known/oauth-protected-resource
          policies:
            cors:
              allowHeaders:
              - mcp-protocol-version
              - content-type
              - authorization
              allowOrigins:
              - '*'
              exposeHeaders:
              - Mcp-Session-Id
            mcpAuthentication:
              mode: strict
              issuer: https://auth.nutgraf.in
              audiences:
              - https://api.nutgraf.in/mcp
              jwks:
                url: http://ory-hydra-public.ory-system.svc.cluster.local:4444/.well-known/jwks.json
              resourceMetadata:
                resource: https://api.nutgraf.in/mcp
                scopesSupported:
                - tenant:read
                - tenant:write
                - cluster:read
                - cluster:write
                - offline_access
                - openid
                bearerMethodsSupported:
                - header
