replicaCount: 1

config:
  inClusterContextName: "hub"
  sessionTTL: 86400
  oidc:
    clientID: "d32a30f0-f2b1-4a11-b3e9-d1e0aec4af6d"
    issuerURL: "https://auth.dev.nutgraf.in"
    scopes: "openid,profile,email,groups"
    callbackURL: "https://dashboard.dev.nutgraf.in/oidc-callback"
    useAccessToken: false
    usePKCE: true
    secret:
      create: false
  pluginsDir: "/headlamp/plugins"
  staticPlugins:
    enabled: true
  enableHelm: true

service:
  type: ClusterIP
  port: 80

clusterRoleBinding:
  create: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 512Mi

podDisruptionBudget:
  enabled: true
  minAvailable: 1

ingress:
  enabled: false

unsafeUseServiceAccountToken: false
