apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: agentgateway-oidc-cookie-secret
  namespace: platform-edge
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: infisical-backend
    kind: ClusterSecretStore

  target:
    name: agentgateway-oidc-cookie-secret
    creationPolicy: Owner

  data:
    - secretKey: oidc-cookie-secret
      remoteRef:
        key: agentgateway-oidc-cookie-secret
