# Vendored from helm chart external-secrets v2.2.0 (charts.external-secrets.io)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-cert-controller
  namespace: external-secrets
  labels:
    helm.sh/chart: external-secrets-2.2.0
    app.kubernetes.io/name: external-secrets-cert-controller
    app.kubernetes.io/instance: eso
    app.kubernetes.io/version: v2.2.0
    app.kubernetes.io/managed-by: Helm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eso-external-secrets
  namespace: external-secrets
  labels:
    helm.sh/chart: external-secrets-2.2.0
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: eso
    app.kubernetes.io/version: v2.2.0
    app.kubernetes.io/managed-by: Helm
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-webhook
  namespace: external-secrets
  labels:
    helm.sh/chart: external-secrets-2.2.0
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/instance: eso
    app.kubernetes.io/version: v2.2.0
    app.kubernetes.io/managed-by: Helm
---
apiVersion: v1
kind: Secret
metadata:
  name: eso-external-secrets-webhook
  namespace: external-secrets
  labels:
    helm.sh/chart: external-secrets-2.2.0
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/instance: eso
    app.kubernetes.io/version: v2.2.0
    app.kubernetes.io/managed-by: Helm
    external-secrets.io/component: webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eso-external-secrets-cert-controller
  labels:
    helm.sh/chart: external-secrets-2.2.0
    app.kubernetes.io/name: external-secrets-cert-controller
    app.kubernetes.io/instance: eso
    app.kubernetes.io/version: v2.2.0
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  resourceNames:
  - secretstore-validate
  - externalsecret-validate
  verbs:
  - update
  - patch
- apiGroups:
  - ''
  resources:
  - endpoints
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eso-external-secrets-controller
  labels:
    helm.sh/chart: external-secrets-2.2.0
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: eso
    app.kubernetes.io/version: v2.2.0
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - external-secrets.io
  resources:
  - secretstores
  - clustersecretstores
  - externalsecrets
  - clusterexternalsecrets
  - pushsecrets
  - clusterpushsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  - externalsecrets/status
  - externalsecrets/finalizers
  - secretstores
  - secretstores/status
  - secretstores/finalizers
  - clustersecretstores
  - clustersecretstores/status
  - clustersecretstores/finalizers
  - clusterexternalsecrets
  - clusterexternalsecrets/status
  - clusterexternalsecrets/finalizers
  - pushsecrets
  - pushsecrets/status
  - pushsecrets/finalizers
  - clusterpushsecrets
  - clusterpushsecrets/status
  - clusterpushsecrets/finalizers
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - generators.external-secrets.io
  resources:
  - generatorstates
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - generators.external-secrets.io
  resources:
  - acraccesstokens
  - cloudsmithaccesstokens
  - clustergenerators
  - ecrauthorizationtokens
  - fakes
  - gcraccesstokens
  - githubaccesstokens
  - quayaccesstokens
  - passwords
  - sshkeys
  - stssessiontokens
  - uuids
  - vaultdynamicsecrets
  - webhooks
  - grafanas
  - mfas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - serviceaccounts
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - update
  - patch
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups:
  - ''
  resources:
  - serviceaccounts/token
  verbs:
  - create
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  verbs:
  - create
  - update
  - delete
- apiGroups:
  - external-secrets.io
  resources:
  - pushsecrets
  verbs:
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eso-external-secrets-view
  labels:
    helm.sh/chart: external-secrets-2.2.0
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: eso
    app.kubernetes.io/version: v2.2.0
    app.kubernetes.io/managed-by: Helm
    rbac.authorization.k8s.io/aggregate-to-view: 'true'
    rbac.authorization.k8s.io/aggregate-to-edit: 'true'
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
rules:
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  - secretstores
  - clustersecretstores
  - pushsecrets
  - clusterpushsecrets
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - generators.external-secrets.io
  resources:
  - acraccesstokens
  - cloudsmithaccesstokens
  - clustergenerators
  - ecrauthorizationtokens
  - fakes
  - gcraccesstokens
  - githubaccesstokens
  - quayaccesstokens
  - passwords
  - sshkeys
  - vaultdynamicsecrets
  - webhooks
  - grafanas
  - generatorstates
  - mfas
  - uuids
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eso-external-secrets-edit
  labels:
    helm.sh/chart: external-secrets-2.2.0
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: eso
    app.kubernetes.io/version: v2.2.0
    app.kubernetes.io/managed-by: Helm
    rbac.authorization.k8s.io/aggregate-to-edit: 'true'
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
rules:
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  - secretstores
  - clustersecretstores
  - pushsecrets
  - clusterpushsecrets
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - generators.external-secrets.io
  resources:
  - acraccesstokens
  - cloudsmithaccesstokens
  - clustergenerators
  - ecrauthorizationtokens
  - fakes
  - gcraccesstokens
  - githubaccesstokens
  - quayaccesstokens
  - passwords
  - sshkeys
  - vaultdynamicsecrets
  - webhooks
  - grafanas
  - generatorstates
  - mfas
  - uuids
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eso-external-secrets-servicebindings
  labels:
    servicebinding.io/controller: 'true'
    helm.sh/chart: external-secrets-2.2.0
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: eso
    app.kubernetes.io/version: v2.2.0
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  - pushsecrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eso-external-secrets-cert-controller
  labels:
    helm.sh/chart: external-secrets-2.2.0
    app.kubernetes.io/name: external-secrets-cert-controller
    app.kubernetes.io/instance: eso
    app.kubernetes.io/version: v2.2.0
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eso-external-secrets-cert-controller
subjects:
- name: external-secrets-cert-controller
  namespace: external-secrets
  kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eso-external-secrets-controller
  labels:
    helm.sh/chart: external-secrets-2.2.0
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: eso
    app.kubernetes.io/version: v2.2.0
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eso-external-secrets-controller
subjects:
- name: eso-external-secrets
  namespace: external-secrets
  kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-external-secrets-leaderelection
  namespace: external-secrets
  labels:
    helm.sh/chart: external-secrets-2.2.0
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: eso
    app.kubernetes.io/version: v2.2.0
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  resourceNames:
  - external-secrets-controller
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eso-external-secrets-leaderelection
  namespace: external-secrets
  labels:
    helm.sh/chart: external-secrets-2.2.0
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: eso
    app.kubernetes.io/version: v2.2.0
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eso-external-secrets-leaderelection
subjects:
- kind: ServiceAccount
  name: eso-external-secrets
  namespace: external-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: eso-external-secrets-webhook
  namespace: external-secrets
  labels:
    helm.sh/chart: external-secrets-2.2.0
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/instance: eso
    app.kubernetes.io/version: v2.2.0
    app.kubernetes.io/managed-by: Helm
    external-secrets.io/component: webhook
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: webhook
    protocol: TCP
    name: webhook
  selector:
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/instance: eso
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eso-external-secrets-cert-controller
  namespace: external-secrets
  labels:
    helm.sh/chart: external-secrets-2.2.0
    app.kubernetes.io/name: external-secrets-cert-controller
    app.kubernetes.io/instance: eso
    app.kubernetes.io/version: v2.2.0
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets-cert-controller
      app.kubernetes.io/instance: eso
  template:
    metadata:
      labels:
        helm.sh/chart: external-secrets-2.2.0
        app.kubernetes.io/name: external-secrets-cert-controller
        app.kubernetes.io/instance: eso
        app.kubernetes.io/version: v2.2.0
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: external-secrets-cert-controller
      automountServiceAccountToken: true
      hostNetwork: false
      containers:
      - name: cert-controller
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        image: ghcr.io/external-secrets/external-secrets:v2.2.0
        imagePullPolicy: IfNotPresent
        args:
        - certcontroller
        - --crd-requeue-interval=5m
        - --service-name=eso-external-secrets-webhook
        - --service-namespace=external-secrets
        - --secret-name=eso-external-secrets-webhook
        - --secret-namespace=external-secrets
        - --metrics-addr=:8080
        - --healthz-addr=:8081
        - --loglevel=info
        - --zap-time-encoding=epoch
        - --enable-partial-cache=true
        ports:
        - containerPort: 8080
          protocol: TCP
          name: metrics
        - containerPort: 8081
          protocol: TCP
          name: ready
        readinessProbe:
          httpGet:
            port: ready
            path: /readyz
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eso-external-secrets
  namespace: external-secrets
  labels:
    helm.sh/chart: external-secrets-2.2.0
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/instance: eso
    app.kubernetes.io/version: v2.2.0
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
      app.kubernetes.io/instance: eso
  template:
    metadata:
      labels:
        helm.sh/chart: external-secrets-2.2.0
        app.kubernetes.io/name: external-secrets
        app.kubernetes.io/instance: eso
        app.kubernetes.io/version: v2.2.0
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: eso-external-secrets
      automountServiceAccountToken: true
      hostNetwork: false
      containers:
      - name: external-secrets
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        image: ghcr.io/external-secrets/external-secrets:v2.2.0
        imagePullPolicy: IfNotPresent
        args:
        - --concurrent=1
        - --metrics-addr=:8080
        - --loglevel=info
        - --zap-time-encoding=epoch
        ports:
        - containerPort: 8080
          protocol: TCP
          name: metrics
      dnsPolicy: ClusterFirst
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eso-external-secrets-webhook
  namespace: external-secrets
  labels:
    helm.sh/chart: external-secrets-2.2.0
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/instance: eso
    app.kubernetes.io/version: v2.2.0
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets-webhook
      app.kubernetes.io/instance: eso
  template:
    metadata:
      labels:
        helm.sh/chart: external-secrets-2.2.0
        app.kubernetes.io/name: external-secrets-webhook
        app.kubernetes.io/instance: eso
        app.kubernetes.io/version: v2.2.0
        app.kubernetes.io/managed-by: Helm
    spec:
      hostNetwork: false
      serviceAccountName: external-secrets-webhook
      automountServiceAccountToken: true
      containers:
      - name: webhook
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        image: ghcr.io/external-secrets/external-secrets:v2.2.0
        imagePullPolicy: IfNotPresent
        args:
        - webhook
        - --port=10250
        - --dns-name=eso-external-secrets-webhook.external-secrets.svc
        - --cert-dir=/tmp/certs
        - --check-interval=5m
        - --metrics-addr=:8080
        - --healthz-addr=:8081
        - --loglevel=info
        - --zap-time-encoding=epoch
        ports:
        - containerPort: 8080
          protocol: TCP
          name: metrics
        - containerPort: 10250
          protocol: TCP
          name: webhook
        - containerPort: 8081
          protocol: TCP
          name: ready
        readinessProbe:
          httpGet:
            port: ready
            path: /readyz
          initialDelaySeconds: 20
          periodSeconds: 5
        volumeMounts:
        - name: certs
          mountPath: /tmp/certs
          readOnly: true
      volumes:
      - name: certs
        secret:
          secretName: eso-external-secrets-webhook
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: secretstore-validate
  labels:
    helm.sh/chart: external-secrets-2.2.0
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/instance: eso
    app.kubernetes.io/version: v2.2.0
    app.kubernetes.io/managed-by: Helm
    external-secrets.io/component: webhook
webhooks:
- name: validate.secretstore.external-secrets.io
  rules:
  - apiGroups:
    - external-secrets.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - secretstores
    scope: Namespaced
  clientConfig:
    service:
      namespace: external-secrets
      name: eso-external-secrets-webhook
      path: /validate-external-secrets-io-v1-secretstore
  admissionReviewVersions:
  - v1
  - v1beta1
  sideEffects: None
  timeoutSeconds: 5
  failurePolicy: Fail
- name: validate.clustersecretstore.external-secrets.io
  rules:
  - apiGroups:
    - external-secrets.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - clustersecretstores
    scope: Cluster
  clientConfig:
    service:
      namespace: external-secrets
      name: eso-external-secrets-webhook
      path: /validate-external-secrets-io-v1-clustersecretstore
  admissionReviewVersions:
  - v1
  - v1beta1
  sideEffects: None
  timeoutSeconds: 5
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: externalsecret-validate
  labels:
    helm.sh/chart: external-secrets-2.2.0
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/instance: eso
    app.kubernetes.io/version: v2.2.0
    app.kubernetes.io/managed-by: Helm
    external-secrets.io/component: webhook
webhooks:
- name: validate.externalsecret.external-secrets.io
  rules:
  - apiGroups:
    - external-secrets.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - externalsecrets
    scope: Namespaced
  clientConfig:
    service:
      namespace: external-secrets
      name: eso-external-secrets-webhook
      path: /validate-external-secrets-io-v1-externalsecret
  admissionReviewVersions:
  - v1
  - v1beta1
  sideEffects: None
  timeoutSeconds: 5
  failurePolicy: Fail
