package infisical

import (
	"context"
	"fmt"

	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/log"

	corev1 "k8s.io/api/core/v1"
	infisicalclient "github.com/soloz-io/zero-ops/operators/hub-operator/internal/client"
	"github.com/soloz-io/zero-ops/operators/hub-operator/internal/secrets"
)

// ApplicationSecretUploader handles uploading application secrets directly to Infisical
// Separation of Concerns: This class generates passwords and uploads to Infisical only
// It does NOT create K8s secrets - ESO creates them by syncing from Infisical
type ApplicationSecretUploader struct {
	k8sClient         client.Client
	uncachedK8sClient client.Client
}

// NewApplicationSecretUploader creates a new application secret uploader
func NewApplicationSecretUploader(k8sClient, uncachedK8sClient client.Client) *ApplicationSecretUploader {
	return &ApplicationSecretUploader{
		k8sClient:         k8sClient,
		uncachedK8sClient: uncachedK8sClient,
	}
}

// UploadApplicationSecrets uploads application secrets directly to Infisical
// These secrets are generated by the operator but never created in K8s
// ESO will create them in K8s by syncing from Infisical
func (u *ApplicationSecretUploader) UploadApplicationSecrets(ctx context.Context) error {
	logger := log.FromContext(ctx)

	// Create Infisical client
	infisicalClient, err := infisicalclient.NewInfisicalClient(ctx, u.uncachedK8sClient, "")
	if err != nil {
		return fmt.Errorf("failed to create Infisical client: %w", err)
	}

	// Get project configuration
	adminSecret := &corev1.Secret{}
	if err := u.uncachedK8sClient.Get(ctx, client.ObjectKey{
		Name:      SecretInfisicalAdmin,
		Namespace: NamespaceOps,
	}, adminSecret); err != nil {
		return fmt.Errorf("failed to get infisical-admin secret: %w", err)
	}

	projectSlug := string(adminSecret.Data[KeyProjectSlug])
	environmentSlug := EnvironmentSlug
	secretPath := "/"

	logger.Info("Uploading application secrets to Infisical", "count", len(ApplicationSecretMappings))

	const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()-_=+[]{}|;:,.<>?"

	for _, secretDef := range ApplicationSecretMappings {
		logger.Info("Processing application secret", "description", secretDef.Description)

		// Upload username if this is a database credential (UsernameKey is not empty)
		if secretDef.UsernameKey != "" {
			if err := infisicalClient.CreateOrUpdateSecretRaw(ctx, projectSlug, environmentSlug, secretPath, secretDef.UsernameKey, secretDef.Username); err != nil {
				logger.Error(err, "Failed to upload username to Infisical", "key", secretDef.UsernameKey)
				continue
			}
			logger.Info("Uploaded username to Infisical", "key", secretDef.UsernameKey, "value", secretDef.Username)
		}

		// Generate and upload password/secret
		// Use 64 chars for system secrets (no username), 32 chars for database passwords
		length := 32
		if secretDef.UsernameKey == "" {
			length = 64
		}

		password, err := secrets.GenerateSecurePasswordWithCharset(length, charset)
		if err != nil {
			logger.Error(err, "Failed to generate password", "key", secretDef.PasswordKey)
			continue
		}

		if err := infisicalClient.CreateOrUpdateSecretRaw(ctx, projectSlug, environmentSlug, secretPath, secretDef.PasswordKey, password); err != nil {
			logger.Error(err, "Failed to upload password to Infisical", "key", secretDef.PasswordKey)
			continue
		}
		logger.Info("Uploaded password to Infisical", "key", secretDef.PasswordKey)
	}

	logger.Info("Application secrets upload complete")
	return nil
}
