// DEPRECATED: Application secret generation by the Hub Operator is prohibited by ADR-003,
// ADR-039, and ADR-043. Application secrets must be created directly in the Infisical UI
// (System of Record) and delivered via ESO. This file is retained for temporary backward
// compatibility only and MUST be removed once all application secrets are migrated to
// Infisical UI → ESO delivery.

package infisical

import (
	"context"
	"encoding/hex"
	"fmt"
	"os"
	"time"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/log"

	"github.com/golang-jwt/jwt/v5"
	infisicalclient "github.com/soloz-io/zero-ops/operators/hub-operator/internal/client"
	"github.com/soloz-io/zero-ops/operators/hub-operator/internal/secrets"
)

// ApplicationSecretUploader handles uploading application secrets directly to Infisical
// Separation of Concerns: This class generates passwords and uploads to Infisical only
// It does NOT create K8s secrets - ESO creates them by syncing from Infisical
type ApplicationSecretUploader struct {
	k8sClient         client.Client
	uncachedK8sClient client.Client
}

// NewApplicationSecretUploader creates a new application secret uploader
func NewApplicationSecretUploader(k8sClient, uncachedK8sClient client.Client) *ApplicationSecretUploader {
	return &ApplicationSecretUploader{
		k8sClient:         k8sClient,
		uncachedK8sClient: uncachedK8sClient,
	}
}

// UploadApplicationSecrets uploads application secrets directly to Infisical
// These secrets are generated by the operator but never created in K8s
// ESO will create them in K8s by syncing from Infisical
//
// IDEMPOTENCY: Checks if secret exists in Infisical before generating new password
// This prevents password rotation on every reconciliation (Requirement: Phase 5 fix)
func (u *ApplicationSecretUploader) UploadApplicationSecrets(ctx context.Context) error {
	logger := log.FromContext(ctx)

	// Create Infisical client
	infisicalClient, err := infisicalclient.NewInfisicalClient(ctx, u.uncachedK8sClient, "")
	if err != nil {
		return fmt.Errorf("failed to create Infisical client: %w", err)
	}

	// Get project slug from environment variable (set via configmap hub-bootstrap-config)
	// Use secrets project for application secrets (hub-secrets is type "secret-manager")
	// Fall back to INFISICAL_PROJECT_SLUG for backward compatibility
	projectSlug := os.Getenv("INFISICAL_SECRETS_PROJECT_SLUG")
	if projectSlug == "" {
		projectSlug = os.Getenv("INFISICAL_PROJECT_SLUG")
	}
	if projectSlug == "" {
		return fmt.Errorf("neither INFISICAL_SECRETS_PROJECT_SLUG nor INFISICAL_PROJECT_SLUG environment variable is set")
	}

	environmentSlug := EnvironmentSlug
	secretPath := "/"

	logger.Info("Uploading application secrets to Infisical", "count", len(ApplicationSecretMappings))

	// RFC 3986 unreserved characters - safe for URLs without encoding
	const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._~"

	successCount := 0
	skippedCount := 0
	var failedKeys []string

	for _, secretDef := range ApplicationSecretMappings {
		// Cell-scoped secrets belong to a spoke's own prefix, not the root. Writing
		// them here too would leave a fleet-wide copy that no spoke can read and that
		// silently diverges from the per-cell value.
		logger.Info("Processing application secret", "description", secretDef.Description)

		// ====================================================================
		// KEY PAIR GENERATION (ed25519, etc.)
		// ====================================================================
		// Key pair generation follows a different idempotency model than passwords:
		//   both absent    → generate
		//   both present   → validate consistency
		//   private only   → derive public from private (repair)
		//   public only    → ERROR (do not mutate — indicates corruption)
		//   mismatch       → ERROR (do not mutate — indicates corruption)
		if secretDef.KeyType == "ed25519" {
			privExists, err := infisicalClient.SecretExists(ctx, projectSlug, environmentSlug, secretPath, secretDef.PrivateKeyKey)
			if err != nil {
				logger.Error(err, "Failed to check if private key exists in Infisical", "key", secretDef.PrivateKeyKey)
				failedKeys = append(failedKeys, secretDef.PrivateKeyKey)
				continue
			}

			pubExists, err := infisicalClient.SecretExists(ctx, projectSlug, environmentSlug, secretPath, secretDef.PublicKeyKey)
			if err != nil {
				logger.Error(err, "Failed to check if public key exists in Infisical", "key", secretDef.PublicKeyKey)
				failedKeys = append(failedKeys, secretDef.PublicKeyKey)
				continue
			}

			switch {
			case privExists && pubExists:
				// Both exist — validate consistency
				privVal, _, err := infisicalClient.GetSecretValue(ctx, projectSlug, environmentSlug, secretPath, secretDef.PrivateKeyKey)
				if err != nil {
					logger.Error(err, "Failed to read existing private key for validation", "key", secretDef.PrivateKeyKey)
					failedKeys = append(failedKeys, secretDef.PrivateKeyKey)
					continue
				}
				pubVal, _, err := infisicalClient.GetSecretValue(ctx, projectSlug, environmentSlug, secretPath, secretDef.PublicKeyKey)
				if err != nil {
					logger.Error(err, "Failed to read existing public key for validation", "key", secretDef.PublicKeyKey)
					failedKeys = append(failedKeys, secretDef.PublicKeyKey)
					continue
				}
				if err := secrets.ValidateEd25519KeyPair(privVal, pubVal); err != nil {
					logger.Error(err, "DKIM key pair validation failed — key pair is inconsistent, refusing to mutate",
						"privateKey", secretDef.PrivateKeyKey, "publicKey", secretDef.PublicKeyKey)
					failedKeys = append(failedKeys, secretDef.PrivateKeyKey, secretDef.PublicKeyKey)
					continue
				}
				logger.Info("DKIM key pair exists and is consistent, skipping", "selector", secretDef.Selector)
				skippedCount++
				successCount++
				continue

			case privExists && !pubExists:
				// Private exists, public missing — derive public from private (repair)
				privVal, _, err := infisicalClient.GetSecretValue(ctx, projectSlug, environmentSlug, secretPath, secretDef.PrivateKeyKey)
				if err != nil {
					logger.Error(err, "Failed to read private key for public key derivation", "key", secretDef.PrivateKeyKey)
					failedKeys = append(failedKeys, secretDef.PrivateKeyKey)
					continue
				}
				pubB64, err := secrets.DeriveEd25519PublicKeyFromPEM(privVal)
				if err != nil {
					logger.Error(err, "Failed to derive public key from existing private key", "key", secretDef.PrivateKeyKey)
					failedKeys = append(failedKeys, secretDef.PrivateKeyKey)
					continue
				}
				if err := infisicalClient.CreateOrUpdateSecretRaw(ctx, projectSlug, environmentSlug, secretPath, secretDef.PublicKeyKey, pubB64); err != nil {
					logger.Error(err, "Failed to upload derived public key to Infisical", "key", secretDef.PublicKeyKey)
					failedKeys = append(failedKeys, secretDef.PublicKeyKey)
					continue
				}
				logger.Info("Derived and uploaded public key from existing private key", "selector", secretDef.Selector)
				successCount++

			case !privExists && pubExists:
				// Public exists but private missing — indicates corruption, do not mutate
				logger.Error(fmt.Errorf("public key exists but private key is missing"),
					"DKIM key pair is in an inconsistent state — public key without private key indicates corruption. "+
						"Manual intervention required: delete the public key and let the operator regenerate both",
					"privateKey", secretDef.PrivateKeyKey, "publicKey", secretDef.PublicKeyKey)
				failedKeys = append(failedKeys, secretDef.PrivateKeyKey)
				continue

			default:
				// Both missing — generate new key pair
				privPEM, pubB64, err := secrets.GenerateEd25519KeyPair()
				if err != nil {
					logger.Error(err, "Failed to generate Ed25519 key pair", "selector", secretDef.Selector)
					failedKeys = append(failedKeys, secretDef.PrivateKeyKey)
					continue
				}
				if err := infisicalClient.CreateOrUpdateSecretRaw(ctx, projectSlug, environmentSlug, secretPath, secretDef.PrivateKeyKey, privPEM); err != nil {
					logger.Error(err, "Failed to upload private key to Infisical", "key", secretDef.PrivateKeyKey)
					failedKeys = append(failedKeys, secretDef.PrivateKeyKey)
					continue
				}
				if err := infisicalClient.CreateOrUpdateSecretRaw(ctx, projectSlug, environmentSlug, secretPath, secretDef.PublicKeyKey, pubB64); err != nil {
					logger.Error(err, "Failed to upload public key to Infisical", "key", secretDef.PublicKeyKey)
					failedKeys = append(failedKeys, secretDef.PublicKeyKey)
					continue
				}
				logger.Info("Generated and uploaded Ed25519 DKIM key pair", "selector", secretDef.Selector,
					"privateKey", secretDef.PrivateKeyKey, "publicKey", secretDef.PublicKeyKey)
				successCount++
			}
			continue
		}
		// ====================================================================
		// END KEY PAIR GENERATION
		// ====================================================================

		// Upload username if this is a database credential (UsernameKey is not empty)
		if secretDef.UsernameKey != "" {
			// Check if username already exists in Infisical
			usernameExists, err := infisicalClient.SecretExists(ctx, projectSlug, environmentSlug, secretPath, secretDef.UsernameKey)
			if err != nil {
				logger.Error(err, "Failed to check if username exists in Infisical", "key", secretDef.UsernameKey)
				failedKeys = append(failedKeys, secretDef.UsernameKey)
				continue
			}

			if !usernameExists {
				// Username doesn't exist, create it
				if err := infisicalClient.CreateOrUpdateSecretRaw(ctx, projectSlug, environmentSlug, secretPath, secretDef.UsernameKey, secretDef.Username); err != nil {
					logger.Error(err, "Failed to upload username to Infisical", "key", secretDef.UsernameKey)
					failedKeys = append(failedKeys, secretDef.UsernameKey)
					continue
				}
				logger.Info("Uploaded username to Infisical", "key", secretDef.UsernameKey, "value", secretDef.Username)
			} else {
				logger.Info("Username already exists in Infisical, skipping", "key", secretDef.UsernameKey)
			}
		}

		// Check if password already exists in Infisical (IDEMPOTENCY)
		passwordExists, err := infisicalClient.SecretExists(ctx, projectSlug, environmentSlug, secretPath, secretDef.PasswordKey)
		if err != nil {
			logger.Error(err, "Failed to check if password exists in Infisical", "key", secretDef.PasswordKey)
			failedKeys = append(failedKeys, secretDef.PasswordKey)
			continue
		}

		if passwordExists && secretDef.HexBytes > 0 {
			// Present is not the same as usable. Re-check the stored form so a value
			// written before HexBytes existed is repaired rather than preserved.
			if current, found, err := infisicalClient.GetSecretValue(ctx, projectSlug, environmentSlug, secretPath, secretDef.PasswordKey); err != nil {
				logger.Error(err, "Failed to read existing secret for validation; leaving it untouched", "key", secretDef.PasswordKey)
			} else if found && !hexValueIsWellFormed(current, secretDef.HexBytes) {
				logger.Info("Existing secret is malformed for its consumer; regenerating",
					"key", secretDef.PasswordKey, "expectedChars", secretDef.HexBytes*2, "actualChars", len(current))
				passwordExists = false
			}
		}

		if passwordExists {
			// Password already exists in Infisical, skip generation
			logger.Info("Password already exists in Infisical, skipping generation", "key", secretDef.PasswordKey)
			skippedCount++
			successCount++ // Count as success (idempotent operation)
			continue
		}

		// Password doesn't exist, generate and upload.
		// Use 64 chars for system secrets (no username), 32 chars for database passwords.
		// HexBytes overrides the alphabet entirely for consumers that hex-decode the
		// value and require an exact key length.
		var password string
		if secretDef.HexBytes > 0 {
			password, err = secrets.GenerateHexKey(secretDef.HexBytes)
		} else {
			length := 32
			if secretDef.UsernameKey == "" {
				length = 64
			}
			password, err = secrets.GenerateSecurePasswordWithCharset(length, charset)
		}
		if err != nil {
			logger.Error(err, "Failed to generate password", "key", secretDef.PasswordKey)
			failedKeys = append(failedKeys, secretDef.PasswordKey)
			continue
		}

		if err := infisicalClient.CreateOrUpdateSecretRaw(ctx, projectSlug, environmentSlug, secretPath, secretDef.PasswordKey, password); err != nil {
			logger.Error(err, "Failed to upload password to Infisical", "key", secretDef.PasswordKey)
			failedKeys = append(failedKeys, secretDef.PasswordKey)
			continue
		}
		logger.Info("Uploaded password to Infisical", "key", secretDef.PasswordKey)

		// ---> NEW: Intercept Svix signing secret to generate and upload the JWT token <---
		if secretDef.PasswordKey == "openmeter-svix-signing-secret" {
			jwtToken, err := generateSvixJWT(password)
			if err != nil {
				logger.Error(err, "Failed to generate Svix JWT token")
				failedKeys = append(failedKeys, "openmeter-svix-jwt")
				continue
			}
			if err := infisicalClient.CreateOrUpdateSecretRaw(ctx, projectSlug, environmentSlug, secretPath, "openmeter-svix-jwt", jwtToken); err != nil {
				logger.Error(err, "Failed to upload Svix JWT to Infisical", "key", "openmeter-svix-jwt")
				failedKeys = append(failedKeys, "openmeter-svix-jwt")
				continue
			}
			logger.Info("Uploaded Svix JWT to Infisical", "key", "openmeter-svix-jwt")
		}
		// ---> END NEW LOGIC <---

		successCount++
	}

	// Entries carrying CellScopedKey are ALSO produced once per spoke, into
	// /spoke-pool/<cellId>/shared. This is in addition to the root upload above, not
	// instead of it: the hub agentgateway reads the root key while each spoke can
	// only read its own prefix (ADR-031). The cell folder is created by the SpokePool
	// reconciler (EnsureInfisicalCredentials); if it does not exist yet the write
	// fails and the next HubEnvironment reconcile retries, so ordering self-resolves.
	if err := u.uploadCellScopedSecrets(ctx, infisicalClient, projectSlug, environmentSlug); err != nil {
		logger.Error(err, "Cell-scoped application secrets could not be uploaded")
	}

	logger.Info("Application secrets upload complete", "uploaded", successCount, "skipped", skippedCount, "total", len(ApplicationSecretMappings), "failed", len(failedKeys))

	if successCount == 0 && len(ApplicationSecretMappings) > 0 {
		return fmt.Errorf("all %d application secret uploads failed, failed keys: %v", len(ApplicationSecretMappings), failedKeys)
	}

	return nil
}

// generateSvixJWT generates a signed JWT token required by Svix for API authentication
// Svix validates incoming API requests using the signing secret (SVIX_JWT_SECRET)
// OpenMeter must send a JWT token signed with that secret in the Authorization header
// The 'sub' claim must be a valid organization ID in format 'org_XXXXX'
func generateSvixJWT(signingSecret string) (string, error) {
	claims := jwt.MapClaims{
		"iss": "svix-server",
		"sub": "org_openmeter", // Must be valid org ID format
		"iat": time.Now().Unix(),
		"exp": time.Now().Add(10 * 365 * 24 * time.Hour).Unix(), // 10 years validity
	}
	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	return token.SignedString([]byte(signingSecret))
}

// uploadCellScopedSecrets writes every CellScoped mapping into each SpokePool's
// shared path, generating values exactly as the root path does so a cell-scoped
// secret and a fleet-wide one of the same kind can never differ in form. The
// agentgateway cookie key carries HexBytes: 32 because agentgateway hex-decodes it
// and demands exactly 32 bytes; a base64 value of the same 32 bytes is the right
// entropy in the wrong encoding and fails at startup with
// `Invalid character 'Z' at position 1`.
//
// Existing values are left alone: this key signs live browser sessions, so
// regenerating it on a reconcile would invalidate every session on that spoke.
func (u *ApplicationSecretUploader) uploadCellScopedSecrets(
	ctx context.Context, infisicalClient *infisicalclient.InfisicalClient,
	projectSlug, environmentSlug string,
) error {
	logger := log.FromContext(ctx)

	var cellScoped []ApplicationSecretDefinition
	for _, def := range ApplicationSecretMappings {
		if def.CellScopedKey != "" {
			cellScoped = append(cellScoped, def)
		}
	}
	if len(cellScoped) == 0 {
		return nil
	}

	spokes := &unstructured.UnstructuredList{}
	spokes.SetGroupVersionKind(schema.GroupVersionKind{
		Group: "nutgraf.in", Version: "v1alpha1", Kind: "SpokePoolList",
	})
	if err := u.uncachedK8sClient.List(ctx, spokes); err != nil {
		return fmt.Errorf("failed to list SpokePools for cell-scoped secrets: %w", err)
	}

	for _, sp := range spokes.Items {
		cellID := sp.GetName()
		sharedPath := fmt.Sprintf(secrets.InfisicalSharedPathFormat, cellID)
		for _, def := range cellScoped {
			exists, err := infisicalClient.SecretExists(ctx, projectSlug, environmentSlug, sharedPath, def.CellScopedKey)
			if err != nil {
				logger.Error(err, "Failed to check cell-scoped secret", "cell", cellID, "key", def.CellScopedKey)
				continue
			}
			if exists && def.HexBytes > 0 {
				if current, found, err := infisicalClient.GetSecretValue(ctx, projectSlug, environmentSlug, sharedPath, def.CellScopedKey); err != nil {
					logger.Error(err, "Failed to read existing cell secret for validation; leaving it untouched",
						"cell", cellID, "key", def.CellScopedKey)
				} else if found && !hexValueIsWellFormed(current, def.HexBytes) {
					// Rotating this invalidates live sessions on the spoke, which is the
					// lesser harm: while it is malformed agentgateway will not start at
					// all, so there are no sessions to preserve.
					logger.Info("Existing cell secret is malformed for its consumer; regenerating",
						"cell", cellID, "key", def.CellScopedKey,
						"expectedChars", def.HexBytes*2, "actualChars", len(current))
					exists = false
				}
			}
			if exists {
				continue
			}

			var value string
			if def.HexBytes > 0 {
				value, err = secrets.GenerateHexKey(def.HexBytes)
			} else {
				value, err = secrets.GenerateSecurePassword()
			}
			if err != nil {
				logger.Error(err, "Failed to generate cell-scoped secret", "cell", cellID, "key", def.CellScopedKey)
				continue
			}

			if err := infisicalClient.CreateOrUpdateSecretRaw(ctx, projectSlug, environmentSlug, sharedPath, def.CellScopedKey, value); err != nil {
				logger.Error(err, "Failed to upload cell-scoped secret", "cell", cellID, "key", def.CellScopedKey, "path", sharedPath)
				continue
			}
			logger.Info("Uploaded cell-scoped secret", "cell", cellID, "key", def.CellScopedKey, "path", sharedPath)
		}
	}
	return nil
}

// hexValueIsWellFormed reports whether a stored value matches what HexBytes
// promised: exactly hexBytes bytes, hex-encoded.
//
// Existence is not correctness. These keys are consumed by code that hex-decodes
// them and demands an exact length, so a value carrying the right entropy in the
// wrong encoding — base64(32 bytes), 44 chars — is present, plausible, and fatal:
// agentgateway rejects it at startup with `Invalid character 'Z' at position 1`.
// Values predating HexBytes are exactly that shape, and a plain existence check
// preserves them forever.
func hexValueIsWellFormed(value string, hexBytes int) bool {
	if len(value) != hexBytes*2 {
		return false
	}
	_, err := hex.DecodeString(value)
	return err == nil
}
