package infisical

// ============================================================================
// SECRET MAPPINGS REGISTRY
// ============================================================================
// This file is the SINGLE SOURCE OF TRUTH for CLI and Bootstrap secrets uploaded to Infisical.
//
// ARCHITECTURE FLOW (HYBRID PATTERN):
//
// BOOTSTRAP SECRETS (Operator creates → uploads to Infisical → ESO syncs back):
// 1. Operator generates bootstrap secrets in K8s (Phase 1)
// 2. Operator uploads them to Infisical (making Infisical the Source of Truth)
// 3. ExternalSecrets (ESO) syncs them back with creationPolicy: Merge
// 4. Infrastructure components consume (CNPG, Infisical, Redis)
//
// APPLICATION SECRETS (Operator uploads to Infisical → ESO creates in K8s):
// 1. Operator generates passwords and uploads directly to Infisical (Phase 0)
// 2. ExternalSecrets (ESO) creates K8s secrets with creationPolicy: Owner
// 3. Applications consume ESO-managed secrets
// 4. See ApplicationSecretMappings below for application secret definitions
//
// HOW TO ADD A NEW BOOTSTRAP SECRET:
// 1. Add entry to CLISecretMappings below
// 2. Create corresponding ExternalSecret manifest with creationPolicy: Merge
// 3. Operator will automatically upload on next reconciliation
//
// HOW TO ADD A NEW APPLICATION SECRET:
// 1. Add entry to ApplicationSecretMappings below
// 2. Create ExternalSecret manifest with creationPolicy: Owner
// 3. DO NOT add to CLISecretMappings (operator uploads directly to Infisical)
// ============================================================================

// SecretMapping defines how to map a K8s secret to Infisical
type SecretMapping struct {
	SourceNamespace string // K8s namespace where secret exists
	SourceName      string // K8s secret name
	SourceKey       string // Key within the K8s secret
	InfisicalKey    string // Key name in Infisical
	Description     string // Human-readable description for logging
}

// CLISecretMappings is the registry of CLI and Bootstrap secrets to upload to Infisical
//
// ┌─────────────────────────────────────────────────────────────────────────┐
// │ BOOTSTRAP SECRETS (Operator creates, uploads to Infisical)             │
// ├─────────────────────────────────────────────────────────────────────────┤
// │ 1. platform-db-app-username   → CNPG bootstrap superuser              │
// │ 2. platform-db-app-password   → CNPG bootstrap superuser              │
// │ 3. infisical-db-username      → Infisical database user               │
// │ 4. infisical-db-password      → Infisical database user               │
// ├─────────────────────────────────────────────────────────────────────────┤
// │ CLI-INJECTED SECRETS (CLI creates, operator uploads)                   │
// ├─────────────────────────────────────────────────────────────────────────┤
// │ 5. hetzner-dns                → Used by external-dns, cert-manager     │
// │ 6. ghcr-pull-secret           → Used by mcp-server (image pulls)       │
// │ 7. github-username            → Used by ArgoCD (repo access)           │
// │ 8. github-token               → Used by ArgoCD (repo access)           │
// └─────────────────────────────────────────────────────────────────────────┘
//
// ┌─────────────────────────────────────────────────────────────────────────┐
// │ APPLICATION SECRETS (see ApplicationSecretMappings below)               │
// ├─────────────────────────────────────────────────────────────────────────┤
// │ • control-plane-db-credentials  → Uploaded directly to Infisical       │
// │ • hub-db-credentials            → Uploaded directly to Infisical       │
// │ • hydra-db-credentials          → Uploaded directly to Infisical       │
// │ • kratos-db-credentials         → Uploaded directly to Infisical       │
// │ • keto-db-credentials           → Uploaded directly to Infisical       │
// └─────────────────────────────────────────────────────────────────────────┘
var CLISecretMappings = []SecretMapping{
	// ========================================================================
	// BOOTSTRAP SECRETS (Operator creates in Phase 1)
	// ========================================================================

	// ========================================================================
	// 1. PLATFORM-DB-APP USERNAME (CNPG Bootstrap)
	// ========================================================================
	// Purpose: CNPG bootstrap superuser credentials
	// Source: platform-db-app (generated by operator in Phase 1)
	// Consumers: CNPG Cluster bootstrap
	// ExternalSecret: manifests/hub-core-services/platform-database/platform-db-app-credentials-externalsecret.yaml
	// CreationPolicy: Merge (operator creates, ESO updates)
	{
		SourceNamespace: NamespaceData,              // platform-data
		SourceName:      "platform-db-app",          // platform-db-app
		SourceKey:       "username",                 // username
		InfisicalKey:    "platform-db-app-username", // platform-db-app-username
		Description:     "Platform DB app username (CNPG bootstrap)",
	},

	// ========================================================================
	// 2. PLATFORM-DB-APP PASSWORD (CNPG Bootstrap)
	// ========================================================================
	{
		SourceNamespace: NamespaceData,              // platform-data
		SourceName:      "platform-db-app",          // platform-db-app
		SourceKey:       "password",                 // password
		InfisicalKey:    "platform-db-app-password", // platform-db-app-password
		Description:     "Platform DB app password (CNPG bootstrap)",
	},

	// ========================================================================
	// 3. INFISICAL-DB USERNAME (Infisical Bootstrap)
	// ========================================================================
	// Purpose: Infisical database user credentials
	// Source: infisical-db-credentials (generated by operator in Phase 1)
	// Consumers: Infisical deployment
	{
		SourceNamespace: NamespaceData,              // platform-data
		SourceName:      "infisical-db-credentials", // infisical-db-credentials
		SourceKey:       "username",                 // username
		InfisicalKey:    "infisical-db-username",    // infisical-db-username
		Description:     "Infisical DB username (Infisical bootstrap)",
	},

	// ========================================================================
	// 4. INFISICAL-DB PASSWORD (Infisical Bootstrap)
	// ========================================================================
	{
		SourceNamespace: NamespaceData,              // platform-data
		SourceName:      "infisical-db-credentials", // infisical-db-credentials
		SourceKey:       "password",                 // password
		InfisicalKey:    "infisical-db-password",    // infisical-db-password
		Description:     "Infisical DB password (Infisical bootstrap)",
	},

	// ========================================================================
	// CLI-INJECTED SECRETS (Deployed by CLI/ClusterResourceSet)
	// ========================================================================

	// ========================================================================
	// 5. HETZNER DNS API TOKEN
	// ========================================================================
	// Purpose: DNS management for external-dns and cert-manager ACME DNS-01
	// Source: hcloud secret (deployed by CLI via ClusterResourceSet)
	// Consumers: external-dns, cert-manager-webhook-hetzner
	// ExternalSecret: manifests/platform-external-dns/hetzner-dns-externalsecret.yaml
	{
		SourceNamespace: NamespaceCloudSystem, // kube-system
		SourceName:      "hetzner",            // Day-0 secret name
		SourceKey:       "hcloud",             // Key in the secret
		InfisicalKey:    "hcloud-token",       // Unified SOT key in Infisical
		Description:     "Hetzner API token",
	},

	// ========================================================================
	// 5b. EXTERNALLY-ISSUED CREDENTIALS (seeded from k8-secrets/)
	// ========================================================================
	// Purpose: credentials issued by systems OUTSIDE the cluster, which nothing
	// here can generate. They previously had no producer at all: a rebuilt
	// Infisical came up without them, their ExternalSecrets reported only
	// "could not get secret data from provider", and the consuming pods sat in
	// CreateContainerConfigError. Seeding was folklore — an operator had to know
	// which keys to paste into the console.
	// Source: created by scripts/hub-bootstrap.sh (step 6b) from k8-secrets/,
	// which is gitignored. A key whose file is absent or empty is never turned
	// into a Secret, so it is skipped here rather than uploaded blank.
	{
		SourceNamespace: NamespaceOps,
		SourceName:      "s3-object-storage",
		SourceKey:       "access-key-id",
		InfisicalKey:    "S3_ACCESS_KEY_ID",
		Description:     "Hetzner Object Storage access key (CNPG Barman backups)",
	},
	{
		SourceNamespace: NamespaceOps,
		SourceName:      "s3-object-storage",
		SourceKey:       "secret-access-key",
		InfisicalKey:    "S3_SECRET_ACCESS_KEY",
		Description:     "Hetzner Object Storage secret key (CNPG Barman backups)",
	},
	{
		SourceNamespace: NamespaceOps,
		SourceName:      "grafana-cloud",
		SourceKey:       "api-key",
		InfisicalKey:    "GRAFANA_CLOUD_API_KEY",
		Description:     "Grafana Cloud API key (alloy remote write)",
	},
	{
		SourceNamespace: NamespaceOps,
		SourceName:      "grafana-cloud",
		SourceKey:       "prometheus-url",
		InfisicalKey:    "GRAFANA_CLOUD_PROMETHEUS_URL",
		Description:     "Grafana Cloud Prometheus remote-write endpoint",
	},
	{
		SourceNamespace: NamespaceOps,
		SourceName:      "grafana-cloud",
		SourceKey:       "prometheus-user",
		InfisicalKey:    "GRAFANA_CLOUD_PROMETHEUS_USER",
		Description:     "Grafana Cloud Prometheus user id",
	},
	{
		SourceNamespace: NamespaceOps,
		SourceName:      "grafana-cloud",
		SourceKey:       "loki-url",
		InfisicalKey:    "GRAFANA_CLOUD_LOKI_URL",
		Description:     "Grafana Cloud Loki push endpoint",
	},
	{
		SourceNamespace: NamespaceOps,
		SourceName:      "grafana-cloud",
		SourceKey:       "loki-user",
		InfisicalKey:    "GRAFANA_CLOUD_LOKI_USER",
		Description:     "Grafana Cloud Loki user id",
	},

	// ========================================================================
	// 6. GITHUB CONTAINER REGISTRY PULL SECRET
	// ========================================================================
	// Purpose: Pull private images from ghcr.io
	// Source: ghcr-pull-secret (deployed by CLI/manually in platform-ops)
	// Consumers: mcp-server, other private image deployments
	// ExternalSecret: manifests/api-gateway/mcp-server/ghcr-pull-secret-externalsecret.yaml
	{
		SourceNamespace: NamespaceOps,        // platform-ops
		SourceName:      "ghcr-pull-secret",  // ghcr-pull-secret
		SourceKey:       ".dockerconfigjson", // .dockerconfigjson
		InfisicalKey:    "ghcr-pull-secret",  // ghcr-pull-secret
		Description:     "GitHub Container Registry pull secret",
	},

	// ========================================================================
	// 7. GITHUB USERNAME (for ArgoCD)
	// ========================================================================
	// Purpose: GitHub authentication for ArgoCD repository access
	// Source: platform-git-secret (deployed by CLI/bootstrap)
	// Consumers: ArgoCD
	// ExternalSecret: manifests/argocd/argocd-github-creds-externalsecret.yaml
	{
		SourceNamespace: NamespaceOps,          // platform-ops
		SourceName:      "platform-git-secret", // platform-git-secret
		SourceKey:       "username",            // username
		InfisicalKey:    "github-username",     // github-username
		Description:     "GitHub username for ArgoCD",
	},

	// ========================================================================
	// 8. GITHUB TOKEN (for ArgoCD)
	// ========================================================================
	// Purpose: GitHub authentication token for ArgoCD repository access
	// Source: platform-git-secret (deployed by CLI/bootstrap)
	// Consumers: ArgoCD
	// ExternalSecret: manifests/argocd/argocd-github-creds-externalsecret.yaml
	{
		SourceNamespace: NamespaceOps,          // platform-ops
		SourceName:      "platform-git-secret", // platform-git-secret
		SourceKey:       "password",            // password
		InfisicalKey:    "github-token",        // github-token
		Description:     "GitHub token for ArgoCD",
	},

	// ========================================================================
	// ADD NEW BOOTSTRAP/CLI SECRETS BELOW THIS LINE
	// ========================================================================

	// ========================================================================
	// 9. AWS ACCESS KEY ID (for Infisical encryption key recovery)
	// ========================================================================
	// Purpose: AWS Secrets Manager authentication for ENCRYPTION_KEY backup/restore
	// Source: hub-operator-aws-credentials (deployed by CLI)
	// Consumers: hub-operator
	// ExternalSecret: manifests/hub-operator/aws-credentials-externalsecret.yaml
	{
		SourceNamespace: NamespaceOps,                   // platform-ops
		SourceName:      "hub-operator-aws-credentials", // hub-operator-aws-credentials
		SourceKey:       "AWS_ACCESS_KEY_ID",            // AWS_ACCESS_KEY_ID
		InfisicalKey:    "AWS_ACCESS_KEY_ID",            // AWS_ACCESS_KEY_ID
		Description:     "AWS Access Key ID for Secrets Manager",
	},

	// ========================================================================
	// 10. AWS SECRET ACCESS KEY (for Infisical encryption key recovery)
	// ========================================================================
	{
		SourceNamespace: NamespaceOps,                   // platform-ops
		SourceName:      "hub-operator-aws-credentials", // hub-operator-aws-credentials
		SourceKey:       "AWS_SECRET_ACCESS_KEY",        // AWS_SECRET_ACCESS_KEY
		InfisicalKey:    "AWS_SECRET_ACCESS_KEY",        // AWS_SECRET_ACCESS_KEY
		Description:     "AWS Secret Access Key for Secrets Manager",
	},

	// ========================================================================
	// 11. AWS REGION (for Infisical encryption key recovery)
	// ========================================================================
	{
		SourceNamespace: NamespaceOps,                   // platform-ops
		SourceName:      "hub-operator-aws-credentials", // hub-operator-aws-credentials
		SourceKey:       "AWS_REGION",                   // AWS_REGION
		InfisicalKey:    "AWS_REGION",                   // AWS_REGION
		Description:     "AWS Region for Secrets Manager",
	},

	// ========================================================================
	// 12. TAILSCALE AUTHKEY (hybrid spoke CP tailnet join)
	// ========================================================================
	// Purpose: Tailscale auth key for hybrid spoke control-plane nodes (ADR-046)
	// Source: tailscale-hybrid-psk (created by `hub configure-tailscale` from
	//        k8-secrets/tailscale/authkey)
	// Consumers: shared ClusterClass Tailscale pre-kubeadm hook (contentFrom.secret)
	// ExternalSecret: manifests/providers/hybrid/k8s/tailscale-psk-es.yaml
	{
		SourceNamespace: NamespaceCAPI,          // platform-capi
		SourceName:      "tailscale-hybrid-psk", // tailscale-hybrid-psk
		SourceKey:       "authkey",              // authkey
		InfisicalKey:    KeyTailscaleAuthkey,    // tailscale-authkey
		Description:     "Tailscale auth key for hybrid spoke CP",
	},

	// ========================================================================
	// 13. TAILSCALE HOSTNAME (hybrid spoke CP tailnet hostname)
	// ========================================================================
	{
		SourceNamespace: NamespaceCAPI,          // platform-capi
		SourceName:      "tailscale-hybrid-psk", // tailscale-hybrid-psk
		SourceKey:       "hostname",             // hostname
		InfisicalKey:    KeyTailscaleHostname,   // tailscale-hostname
		Description:     "Tailscale hostname for hybrid spoke CP",
	},

	// ========================================================================
	// Template:
	// {
	//     SourceNamespace: "namespace-where-secret-exists",
	//     SourceName:      "k8s-secret-name",
	//     SourceKey:       "key-in-secret-data",
	//     InfisicalKey:    "key-in-infisical",
	//     Description:     "Human readable description",
	// },
}

// ============================================================================
// APPLICATION SECRET DEFINITIONS
// ============================================================================
// Application secrets are generated by the operator and uploaded directly to Infisical
// (never created in K8s by the operator). ESO creates them in K8s with creationPolicy: Owner.

// ApplicationSecretDefinition defines an application secret to create in Infisical
type ApplicationSecretDefinition struct {
	UsernameKey string // Infisical key for username (e.g., "control-plane-db-username") - empty for non-DB secrets
	PasswordKey string // Infisical key for password/secret (e.g., "control-plane-db-password")
	Username    string // Username value (e.g., "mcp_server") - empty for non-DB secrets
	Description string // Human-readable description
}

// ApplicationSecretMappings defines all application secrets to create in Infisical
// These secrets are created directly in Infisical (not in K8s first)
// ESO will sync them to K8s with creationPolicy: Owner
//
// ┌─────────────────────────────────────────────────────────────────────────┐
// │ APPLICATION SECRETS (Operator uploads to Infisical → ESO creates in K8s)│
// ├─────────────────────────────────────────────────────────────────────────┤
// │ 1. control-plane-db-credentials  → mcp_server database user            │
// │ 2. hydra-db-credentials          → hydra database user                 │
// │ 3. kratos-db-credentials         → kratos database user                │
// │ 4. keto-db-credentials           → keto database user                  │
// └─────────────────────────────────────────────────────────────────────────┘
var ApplicationSecretMappings = []ApplicationSecretDefinition{
	{
		UsernameKey: "hub-control-plane-db-username",
		PasswordKey: "hub-control-plane-db-password",
		Username:    "hub_control_plane",
		Description: "Control Plane DB credentials (mcp-server)",
	},

	{
		UsernameKey: "hub-hydra-db-username",
		PasswordKey: "hub-hydra-db-password",
		Username:    "hub_hydra",
		Description: "Hydra DB credentials",
	},
	{
		UsernameKey: "hub-kratos-db-username",
		PasswordKey: "hub-kratos-db-password",
		Username:    "hub_kratos",
		Description: "Kratos DB credentials",
	},
	{
		UsernameKey: "hub-keto-db-username",
		PasswordKey: "hub-keto-db-password",
		Username:    "hub_keto",
		Description: "Keto DB credentials",
	},
	{
		UsernameKey: "",
		PasswordKey: "hub-hydra-system-secret",
		Username:    "",
		Description: "Hydra system secret for cookie/session encryption",
	},
	{
		UsernameKey: "nats-leaf-username",
		PasswordKey: "nats-leaf-password",
		Username:    "leafnode",
		Description: "NATS Leaf Node credentials for spoke clusters",
	},
	{
		UsernameKey: "openmeter-postgresql-username",
		PasswordKey: "openmeter-postgresql-password",
		Username:    "openmeter",
		Description: "OpenMeter PostgreSQL credentials",
	},
	{
		UsernameKey: "",
		PasswordKey: "platform-clickhouse-admin-password",
		Username:    "",
		Description: "Platform ClickHouse admin user password (bootstrap jobs, separate for rotation independence)",
	},
	{
		UsernameKey: "",
		PasswordKey: "openmeter-clickhouse-password",
		Username:    "",
		Description: "OpenMeter ClickHouse user password (logical database access)",
	},
	{
		UsernameKey: "",
		PasswordKey: "openmeter-svix-signing-secret",
		Username:    "",
		Description: "OpenMeter Svix signing secret (also generates JWT token)",
	},
	{
		UsernameKey: "",
		PasswordKey: "hub-kratos-ui-cookie-secret",
		Username:    "",
		Description: "Kratos UI cookie session encryption secret (32-byte random)",
	},
	{
		UsernameKey: "",
		PasswordKey: "hub-kratos-ui-csrf-cookie-secret",
		Username:    "",
		Description: "Kratos UI CSRF cookie secret (32-byte random)",
	},
	// AgentGateway's OIDC session cookie encryption key. It belongs here for the
	// same reason as the two Kratos UI entries above and hub-hydra-system-secret:
	// it is a random value with no external source, so leaving it out of this
	// registry made it the one cookie secret an operator had to seed by hand into
	// a freshly rebuilt Infisical — and nothing said so. The symptom was
	// agentgateway stuck in CreateContainerConfigError while its ExternalSecret
	// reported only "could not get secret data from provider".
	// Consumed as OIDC_COOKIE_SECRET via ExternalSecret
	// manifests/hub-core-services/api-gateway/oidc-cookie-secret-es.yaml
	// (creationPolicy: Owner), which needs no change.
	{
		UsernameKey: "",
		PasswordKey: "agentgateway-oidc-cookie-secret",
		Username:    "",
		Description: "AgentGateway OIDC session cookie encryption secret",
	},
}
