apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s/kind-ingress.yaml
  - k8s/crossplane-provider-docker.yaml
  - k8s/storage-class.yaml
  - k8s/capd-spoke-pool-v1.yaml
  - k8s/spokepool-capd-composition.yaml
  - k8s/metallb-config.yaml
  - k8s/vendor/metallb-native.yaml

