apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spire-server-db-credentials
  namespace: platform-security
  annotations:
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: infisical-backend
    kind: ClusterSecretStore

  target:
    name: spire-server-db-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        server.conf: |
          server {
            bind_address = "0.0.0.0"
            bind_port = "8081"
            trust_domain = "zero-ops.nutgraf.in"
            data_dir = "/run/spire/data"
            log_level = "INFO"
            default_x509_svid_ttl = "1h"
            ca_ttl = "168h"
            ca_subject {
              country = ["US"]
              organization = ["Zero-Ops"]
              common_name = ""
            }
            socket_path = "/spire-server/api.sock"
          }
          plugins {
            DataStore "sql" {
              plugin_data {
                database_type = "postgres"
                connection_string = "host=platform-db-rw.platform-data.svc.cluster.local port=5432 dbname=spire user={{ .username }} password={{ .password }} sslmode=require"
              }
            }
            NodeAttestor "k8s_psat" {
              plugin_data {
                clusters = {
                  "zero-ops-hub" = {
                    service_account_allow_list = ["platform-security:spire-agent"]
                  }
                }
              }
            }
            KeyManager "disk" {
              plugin_data {
                keys_path = "/run/spire/data/keys.json"
              }
            }
            Notifier "k8sbundle" {
              plugin_data {
                namespace = "platform-security"
                config_map = "spire-bundle"
                config_map_key = "bundle.crt"
              }
            }
          }
          health_checks {
            listener_enabled = true
            bind_address = "0.0.0.0"
            bind_port = "8080"
            live_path = "/live"
            ready_path = "/ready"
          }

  data:
    - secretKey: username
      remoteRef:
        key: spire-server-db-username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: spire-server-db-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
