---
boundary: '03'
appName: metrics-server
destinationNamespace: kube-system
isPlatformOwned: 'false'
repoURL: https://kubernetes-sigs.github.io/metrics-server/
targetRevision: 3.12.2
path: ''
chart: metrics-server
directoryRecurse: ''
directoryInclude: ''
helmValues: |
  args:
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi
helmReleaseName: ''
ignoreDifferencesNamespace: ''
extraManifestsPath: ''
