---
boundary: '03'
appName: platform-argocd-github-auth
destinationNamespace: platform-ops
isPlatformOwned: 'true'
repoURL: ''
targetRevision: ''
path: manifests/hub-core-services/argocd-github-auth
chart: ''
directoryRecurse: 'true'
directoryInclude: ''
helmValues: ''
helmReleaseName: ''
ignoreDifferencesNamespace: ''
extraManifestsPath: ''
