apiVersion: v1
kind: Namespace
metadata:
  name: platform-ops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi2argo-controller-manager
  namespace: platform-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: capi2argo-controller-manager
      containers:
      - name: manager
        image: ghcr.io/dntosas/capi2argo-cluster-operator:v1.5.0@sha256:fb8c6457ef6e44d4c4d8a3468feb0d19e973867e0544d6cbc38f837411f3498c
        env:
        - name: ARGOCD_NAMESPACE
          value: "platform-ops"
        - name: ENABLE_GARBAGE_COLLECTION
          value: "true"
