kratos:
  config:
    serve:
      public:
        base_url: https://console.nutgraf.in
        cors:
          enabled: true
    session:
      cookie:
        domain: nutgraf.in
        name: ory_kratos_session
        same_site: Lax
        secure: "true"
    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: file:///etc/config/schemas/identity.schema.json
    oauth2_provider:
      url: http://ory-hydra-admin.hub-platform-identity.svc.cluster.local:4445
      override_return_to: true
    selfservice:
      default_browser_return_url: https://console.nutgraf.in/
      allowed_return_urls:
        - https://auth.nutgraf.in/
        - https://console.nutgraf.in/
        - http://127.0.0.1:6274/oauth/callback
        - http://localhost:6274/oauth/callback
      methods:
        password:
          enabled: true
      flows:
        login:
          ui_url: https://console.nutgraf.in/login
        registration:
          ui_url: https://console.nutgraf.in/registration
    dsn: env://DSN

  automigration:
    enabled: true
    type: initContainer

deployment:
  extraEnv:
    - name: KRATOS_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kratos-db-credentials
          key: password
    - name: DSN
      value: postgres://hub_kratos:$(KRATOS_DB_PASSWORD)@platform-db-rw.hub-platform-data.svc.cluster.local:5432/kratos

  automigration:
    extraEnv:
      - name: KRATOS_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: kratos-db-credentials
            key: password
      - name: DSN
        value: postgres://hub_kratos:$(KRATOS_DB_PASSWORD)@platform-db-rw.hub-platform-data.svc.cluster.local:5432/kratos

  extraVolumes:
    - name: identity-schema
      configMap:
        name: kratos-identity-schema

  extraVolumeMounts:
    - name: identity-schema
      mountPath: /etc/config/schemas
      readOnly: true

  extraInitContainers: |
    - name: wait-for-postgres
      image: postgres:15-alpine
      command: ['sh', '-c', 'until pg_isready -h platform-db-rw.hub-platform-data.svc.cluster.local -p 5432; do sleep 2; done']

