---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - billing.nutgraf.in
  resources:
  - features
  - meters
  - plans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - billing.nutgraf.in
  resources:
  - features/finalizers
  - meters/finalizers
  - plans/finalizers
  verbs:
  - update
- apiGroups:
  - billing.nutgraf.in
  resources:
  - features/status
  - meters/status
  - plans/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.x-k8s.io
  - postgresql.cnpg.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - identity.zeroops.io
  resources:
  - spokemachineidentities
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nutgraf.in
  resources:
  - ainativesaases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nutgraf.in
  resources:
  - ainativesaases/status
  - spokepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nutgraf.in
  resources:
  - spokepools
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ops.nutgraf.in
  resources:
  - hubenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.nutgraf.in
  resources:
  - hubenvironments/finalizers
  verbs:
  - update
- apiGroups:
  - ops.nutgraf.in
  resources:
  - hubenvironments/status
  verbs:
  - get
  - patch
  - update
