//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfisicalConfig) DeepCopyInto(out *InfisicalConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfisicalConfig.
func (in *InfisicalConfig) DeepCopy() *InfisicalConfig {
	if in == nil {
		return nil
	}
	out := new(InfisicalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RevocationPolicy) DeepCopyInto(out *RevocationPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RevocationPolicy.
func (in *RevocationPolicy) DeepCopy() *RevocationPolicy {
	if in == nil {
		return nil
	}
	out := new(RevocationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RotationPolicy) DeepCopyInto(out *RotationPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RotationPolicy.
func (in *RotationPolicy) DeepCopy() *RotationPolicy {
	if in == nil {
		return nil
	}
	out := new(RotationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeMachineIdentity) DeepCopyInto(out *SpokeMachineIdentity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeMachineIdentity.
func (in *SpokeMachineIdentity) DeepCopy() *SpokeMachineIdentity {
	if in == nil {
		return nil
	}
	out := new(SpokeMachineIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpokeMachineIdentity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeMachineIdentityList) DeepCopyInto(out *SpokeMachineIdentityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpokeMachineIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeMachineIdentityList.
func (in *SpokeMachineIdentityList) DeepCopy() *SpokeMachineIdentityList {
	if in == nil {
		return nil
	}
	out := new(SpokeMachineIdentityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpokeMachineIdentityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeMachineIdentitySpec) DeepCopyInto(out *SpokeMachineIdentitySpec) {
	*out = *in
	out.SpokeRef = in.SpokeRef
	out.Infisical = in.Infisical
	if in.RotationPolicy != nil {
		in, out := &in.RotationPolicy, &out.RotationPolicy
		*out = new(RotationPolicy)
		**out = **in
	}
	if in.RevocationPolicy != nil {
		in, out := &in.RevocationPolicy, &out.RevocationPolicy
		*out = new(RevocationPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeMachineIdentitySpec.
func (in *SpokeMachineIdentitySpec) DeepCopy() *SpokeMachineIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(SpokeMachineIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeMachineIdentityStatus) DeepCopyInto(out *SpokeMachineIdentityStatus) {
	*out = *in
	if in.ClientSecretIDs != nil {
		in, out := &in.ClientSecretIDs, &out.ClientSecretIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastRotated != nil {
		in, out := &in.LastRotated, &out.LastRotated
		*out = (*in).DeepCopy()
	}
	if in.NextRotation != nil {
		in, out := &in.NextRotation, &out.NextRotation
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeMachineIdentityStatus.
func (in *SpokeMachineIdentityStatus) DeepCopy() *SpokeMachineIdentityStatus {
	if in == nil {
		return nil
	}
	out := new(SpokeMachineIdentityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpokeRef) DeepCopyInto(out *SpokeRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpokeRef.
func (in *SpokeRef) DeepCopy() *SpokeRef {
	if in == nil {
		return nil
	}
	out := new(SpokeRef)
	in.DeepCopyInto(out)
	return out
}
