apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: victoriametrics-basic-auth
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  refreshInterval: 1h
  
  secretStoreRef:
    name: infisical-backend
    kind: ClusterSecretStore
  
  target:
    name: victoriametrics-basic-auth
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/name: victoriametrics
          app.kubernetes.io/component: auth
      type: Opaque
      data:
        auth: "{{ htpasswd .username .password }}"
  
  data:
    - secretKey: username
      remoteRef:
        key: victoriametrics
        property: username
    - secretKey: password
      remoteRef:
        key: victoriametrics
        property: password
