{{- if .Values.deployXR }}
{{- $databaseName := .Values.database.name | default (printf "tenant-%s-db" .Values.tenantId) -}}
{{- $poolerMaxConn := 5 -}}
{{- $poolerMode := "transaction" -}}
{{- if .Values.pooler -}}
  {{- $poolerMaxConn = .Values.pooler.maxConnections | default 5 -}}
  {{- $poolerMode = .Values.pooler.poolMode | default "transaction" -}}
{{- end -}}
{{- $dbSchema := "public" -}}
{{- $jwtCacheSize := 10000 -}}
{{- if .Values.postgrest -}}
  {{- $dbSchema = .Values.postgrest.dbSchema | default "public" -}}
  {{- $jwtCacheSize = .Values.postgrest.jwtCacheSize | default 10000 -}}
{{- end -}}
---
apiVersion: nutgraf.in/v1alpha1
kind: AINativeSaaS
metadata:
  name: {{ .Values.tenantId }}
  namespace: tenant-{{ .Values.tenantId }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    tenant-id: {{ .Values.tenantId }}
    tier: {{ .Values.tier }}
    cell-id: {{ .Values.cellId }}
spec:
  tenantId: {{ .Values.tenantId }}
  tier: {{ .Values.tier }}
  cellId: {{ .Values.cellId }}
  
  database:
    name: {{ $databaseName }}
    migrations:
      baseline:
        gitRepo: {{ .Values.database.migrations.baseline.gitRepo | default "https://github.com/soloz-io/zero-ops" }}
        gitRevision: {{ .Values.database.migrations.baseline.gitRevision | default "main" }}
        gitPath: {{ .Values.database.migrations.baseline.gitPath | default "migrations/tenant-baseline" }}
      tenant: {{ .Values.database.migrations.tenantSpecific.gitPath | default (printf "fleet-registry/tenants/tenant-%s/migrations/" .Values.tenantId) }}
  
  pooler:
    maxConnections: {{ $poolerMaxConn }}
    poolMode: {{ $poolerMode }}
  
  postgrest:
    dbSchema: {{ $dbSchema }}
    jwtCacheSize: {{ $jwtCacheSize }}
  
  {{- if .Values.resourceQuota }}
  resourceQuota:
    cpu: {{ .Values.resourceQuota.cpu | default "1000m" }}
    memory: {{ .Values.resourceQuota.memory | default "2Gi" }}
    storage: {{ .Values.resourceQuota.storage | default "10Gi" }}
    pods: {{ .Values.resourceQuota.pods | default "10" | quote }}
  {{- end }}
  
  {{- if .Values.ownerEmail }}
  ownerEmail: {{ .Values.ownerEmail }}
  {{- end }}
{{- end }}
