{{- if not .Values.deployXR }}
{{- range .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: tenant-{{ $.Values.tenantId }}
  labels:
    tenant-id: {{ $.Values.tenantId }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .secretStoreRef.name | default "tenant-secret-store" }}
    kind: {{ .secretStoreRef.kind | default "SecretStore" }}
  target:
    name: {{ .name }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
{{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
{{- if .remoteProperty }}
        property: {{ .remoteProperty }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
