---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-{{ .Values.tenantId }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    tenant-id: {{ .Values.tenantId }}
    tier: {{ .Values.tier }}
    app.kubernetes.io/name: tenant-{{ .Values.tenantId }}
    app.kubernetes.io/component: tenant-namespace
    app.kubernetes.io/part-of: zero-ops
