apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-user-groups
  namespace: platform-identity
  labels:
    app.kubernetes.io/part-of: identity
data:
  groups.yaml: |
    users:
      - email: arun4infra@gmail.com
        groups:
          - platform_admins
