apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: capd-spoke-pool-v1
  namespace: platform-capi
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: capd-spoke-pool-control-plane-v1
    machineInfrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        name: capd-spoke-pool-control-plane-machine-v1
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: DockerClusterTemplate
      name: capd-spoke-pool-cluster-v1
  workers:
    machineDeployments:
    - class: default-worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: KubeadmConfigTemplate
            name: capd-spoke-pool-worker-bootstrap-v1
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: DockerMachineTemplate
            name: capd-spoke-pool-worker-machine-v1
  variables:
  - name: controlPlaneMachineType
    required: false
    schema:
      openAPIV3Schema:
        type: string
        default: "m"
  - name: workerMachineType
    required: false
    schema:
      openAPIV3Schema:
        type: string
        default: "m"

  - name: apiServerHost
    required: false
    schema:
      openAPIV3Schema:
        type: string
        default: ""
  - name: apiServerPort
    required: false
    schema:
      openAPIV3Schema:
        type: integer
        default: 0
  patches:
  - name: windowsNetworking
    enabledIf: '{{ ne .apiServerHost "" }}'
    definitions:
    - selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: KubeadmControlPlaneTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: add
        path: /spec/template/spec/kubeadmConfigSpec/clusterConfiguration/apiServer
        value:
          certSANs: []
      - op: add
        path: /spec/template/spec/kubeadmConfigSpec/clusterConfiguration/apiServer/certSANs/-
        valueFrom:
          variable: apiServerHost
  - name: controlPlanePortMapping
    enabledIf: '{{ ne .apiServerHost "" }}'
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachineTemplate
        matchResources:
          machineDeploymentClass:
            names: []
          controlPlane: true
      jsonPatches:
      - op: add
        path: /spec/template/spec/extraPortMappings
        value: []
      - op: add
        path: /spec/template/spec/extraPortMappings/-
        valueFrom:
          template: |
            containerPort: 6443
            hostPort: {{ .apiServerPort }}
            listenAddress: "0.0.0.0"
  - name: controlPlaneEndpoint
    enabledIf: '{{ ne .apiServerHost "" }}'
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerClusterTemplate
        matchResources:
          infrastructureCluster: true
      jsonPatches:
      - op: add
        path: /spec/template/spec/controlPlaneEndpoint
        valueFrom:
          template: |
            host: {{ .apiServerHost }}
            port: {{ .apiServerPort }}

---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerClusterTemplate
metadata:
  name: capd-spoke-pool-cluster-v1
  namespace: platform-capi
spec:
  template:
    spec:
      loadBalancer:
        imageRepository: kindest
        imageTag: v20260131-7181c60a
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlaneTemplate
metadata:
  name: capd-spoke-pool-control-plane-v1
  namespace: platform-capi
spec:
  template:
    spec:
      kubeadmConfigSpec:
        preKubeadmCommands: []
        clusterConfiguration:
          networking:
            podSubnet: 10.244.0.0/16
            serviceSubnet: 10.96.0.0/12
        initConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cgroup-driver: cgroupfs
        joinConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cgroup-driver: cgroupfs
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: capd-spoke-pool-control-plane-machine-v1
  namespace: platform-capi
spec:
  template:
    spec:
      customImage: kindest/node:v1.31.6
      extraMounts:
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: capd-spoke-pool-worker-bootstrap-v1
  namespace: platform-capi
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cgroup-driver: cgroupfs
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DockerMachineTemplate
metadata:
  name: capd-spoke-pool-worker-machine-v1
  namespace: platform-capi
spec:
  template:
    spec:
      customImage: kindest/node:v1.31.6
