apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-creds
  namespace: platform-ops
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: infisical-backend
    kind: ClusterSecretStore

  target:
    name: platform-git-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
          app.kubernetes.io/part-of: argocd
      type: Opaque
      data:
        type: git
        url: https://github.com/soloz-io/zero-ops
        username: "{{ .username }}"
        password: "{{ .password }}"

  data:
    - secretKey: username
      remoteRef:
        key: github-username
    - secretKey: password
      remoteRef:
        key: github-token
