apiVersion: v1
kind: Secret
metadata:
  name: hetzner-credentials
  namespace: {{.Namespace}}
  labels:
    clusterctl.cluster.x-k8s.io/move: ""
type: Opaque
stringData:
  hcloud: {{.HCloudToken}}
  hetzner-robot-user: ""
  hetzner-robot-password: ""
  hcloud-ssh-key-name: ""
