apiVersion: infisical-issuer.infisical.com/v1alpha1
kind: ClusterIssuer
metadata:
  name: infisical-fleet-issuer
spec:
  url: http://infisical-standalone-infisical.platform-security.svc:8080
  projectId: 0f6b52d3-9643-4f8b-9047-1e8b22b4af16
  authentication:
    universalAuth:
      clientId: b87ade3c-5b00-4e57-8dab-22bca886edef
