apiVersion: infisical-issuer.infisical.com/v1alpha1
kind: ClusterIssuer
metadata:
  name: infisical-fleet-issuer
spec:
  url: http://infisical-standalone-infisical.platform-security.svc:8080
  projectId: 20958df6-ac81-4e11-8259-d1ddd1becb5c
  authentication:
    universalAuth:
      clientId: 9b1bbfd0-0065-4228-ad30-e218f1296cd6
