apiVersion: infisical-issuer.infisical.com/v1alpha1
kind: ClusterIssuer
metadata:
  name: infisical-fleet-issuer
spec:
  url: http://infisical-standalone-infisical.platform-security.svc:8080
  projectId: 41876f0d-f915-4715-a4b3-d2d080925f4a
  authentication:
    universalAuth:
      clientId: 4d3ea43c-f91a-4d74-8a5f-529b5cf46410
