---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: capi2argo-controller-manager
  namespace: platform-ops
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi2argo-controller-manager
  namespace: platform-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: capi2argo-controller-manager
      containers:
      - name: manager
        image: ghcr.io/dntosas/capi2argo-cluster-operator:latest
        env:
        - name: ARGOCD_NAMESPACE
          value: "platform-ops"
        - name: ENABLE_GARBAGE_COLLECTION
          value: "true"
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
