apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnpg-controller-manager
  namespace: cnpg-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnpg-controller-manager
  template:
    metadata:
      labels:
        app: cnpg-controller-manager
    spec:
      containers:
      - name: manager
        image: ghcr.io/cloudnative-pg/cloudnative-pg:1.21.0
