// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTenants = `-- name: CountTenants :one
SELECT COUNT(*) FROM tenants
WHERE
    ($1 = '' OR status = $1)
    AND ($2 = '' OR plan = $2)
    AND deleted_at IS NULL
`

type CountTenantsParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) CountTenants(ctx context.Context, arg CountTenantsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTenants, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, org_id, name, email, plan, status, quotas, metadata, created_at, updated_at, deleted_at FROM tenants
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Email,
		&i.Plan,
		&i.Status,
		&i.Quotas,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, org_id, name, email, plan, status, quotas, metadata, created_at, updated_at, deleted_at FROM tenants
WHERE
    ($1 = '' OR status = $1)
    AND ($2 = '' OR plan = $2)
    AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3
OFFSET $4
`

type ListTenantsParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Email,
			&i.Plan,
			&i.Status,
			&i.Quotas,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTenant = `-- name: SoftDeleteTenant :exec
UPDATE tenants
SET
    status = 'deleted',
    deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTenant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTenant, id)
	return err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET
    plan = COALESCE($2::text, plan),
    status = COALESCE($3::text, status),
    quotas = COALESCE($4::jsonb, quotas),
    metadata = COALESCE($5::jsonb, metadata)
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, org_id, name, email, plan, status, quotas, metadata, created_at, updated_at, deleted_at
`

type UpdateTenantParams struct {
	ID       pgtype.UUID `json:"id"`
	Plan     pgtype.Text `json:"plan"`
	Status   pgtype.Text `json:"status"`
	Quotas   []byte      `json:"quotas"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.ID,
		arg.Plan,
		arg.Status,
		arg.Quotas,
		arg.Metadata,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Email,
		&i.Plan,
		&i.Status,
		&i.Quotas,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertTenant = `-- name: UpsertTenant :one
INSERT INTO tenants (
    id,
    org_id,
    name,
    email,
    plan,
    status,
    quotas,
    metadata,
    created_at,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    'active',
    $6,
    $7,
    now(),
    now()
)
ON CONFLICT (name) WHERE deleted_at IS NULL
DO UPDATE
SET
    updated_at = tenants.updated_at
WHERE tenants.deleted_at IS NULL
RETURNING
    id, org_id, name, email, plan, status, quotas, metadata, created_at, updated_at, deleted_at,
    (tenants.created_at = tenants.updated_at) AS created
`

type UpsertTenantParams struct {
	ID       pgtype.UUID `json:"id"`
	OrgID    pgtype.UUID `json:"org_id"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	Plan     string      `json:"plan"`
	Quotas   []byte      `json:"quotas"`
	Metadata []byte      `json:"metadata"`
}

type UpsertTenantRow struct {
	ID        pgtype.UUID      `json:"id"`
	OrgID     pgtype.UUID      `json:"org_id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Plan      string           `json:"plan"`
	Status    string           `json:"status"`
	Quotas    []byte           `json:"quotas"`
	Metadata  []byte           `json:"metadata"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
	Created   bool             `json:"created"`
}

func (q *Queries) UpsertTenant(ctx context.Context, arg UpsertTenantParams) (UpsertTenantRow, error) {
	row := q.db.QueryRow(ctx, upsertTenant,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Email,
		arg.Plan,
		arg.Quotas,
		arg.Metadata,
	)
	var i UpsertTenantRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Email,
		&i.Plan,
		&i.Status,
		&i.Quotas,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Created,
	)
	return i, err
}
