apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    chart: external-dns
    targetRevision: "1.20.0"
    helm:
      values: |
        provider:
          name: webhook
          webhook:
            image:
              repository: ghcr.io/mconfalonieri/external-dns-hetzner-webhook
              tag: v0.12.0
            env:
              - name: HETZNER_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: hetzner-dns
                    key: api-key
        txtOwnerId: zero-ops-mothership
        domainFilters:
          - nutgraf.in
        sources:
          - ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 15
      backoff:
        duration: 30s
        maxDuration: 10m
