apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: platform-ops
  annotations:
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    chart: external-dns
    targetRevision: "1.20.0"
    helm:
      values: |
        provider:
          name: webhook
          webhook:
            image:
              repository: docker.io/hetzner/external-dns-hetzner-webhook
              tag: v0.3.2
            env:
              - name: HETZNER_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: hetzner-dns
                    key: api-key
        txtOwnerId: zero-ops-mothership
        domainFilters:
          - nutgraf.in
        managedRecordTypes:
          - A
          - CNAME
        sources:
          - ingress
          - service
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-edge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 15
      backoff:
        duration: 30s
        maxDuration: 10m
