apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcloud-ccm
  namespace: hub-platform-ops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://charts.hetzner.cloud
    chart: hcloud-cloud-controller-manager
    targetRevision: "1.20.0"
    helm:
      values: |
        env:
          HCLOUD_TOKEN:
            valueFrom:
              secretKeyRef:
                name: hcloud
                key: token
        networking:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: hub-cloud-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 15
      backoff:
        duration: 30s
        maxDuration: 10m
