apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoriametrics-ingress
  namespace: platform-ops
  annotations:
spec:
  project: default
  source:
    repoURL: https://github.com/soloz-io/zero-ops.git
    targetRevision: main
    path: manifests/hub-core-services/victoriametrics
    directory:
      include: "ingress.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
