apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: hub-platform-ops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: "4.15.0"
    helm:
      values: |
        controller:
          admissionWebhooks:
            enabled: false
          service:
            type: LoadBalancer
            annotations:
              load-balancer.hetzner.cloud/location: fsn1
          extraArgs:
            enable-ssl-passthrough: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: hub-platform-edge
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 15
      backoff:
        duration: 30s
        maxDuration: 10m
