apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-external-secrets
  namespace: platform-ops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 2.2.0
    helm:
      values: |
        installCRDs: false

        crds:
          createClusterExternalSecret: true
          createClusterSecretStore: true
          createSecretStore: true
          createClusterGenerator: true
          createClusterPushSecret: true
          createPushSecret: true

        replicaCount: 1

        processClusterPushSecret: true
        processPushSecret: true

        image:
          repository: ghcr.io/external-secrets/external-secrets
          tag: "v2.2.0"
          pullPolicy: IfNotPresent

        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 128Mi

        processClusterExternalSecret: true
        processClusterStore: true
        processSecretStore: true

        metrics:
          service:
            enabled: true
            port: 8080

        serviceMonitor:
          enabled: true
          interval: 30s

        securityContext:
          enabled: true
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-ops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 15
      backoff:
        duration: 30s
        maxDuration: 10m
