apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-cluster-secret-store
  namespace: hub-platform-ops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/soloz-io/zero-ops
    targetRevision: HEAD
    path: manifests/platform-core-services/platform-cluster-secret-store
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: hub-platform-ops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 15
      backoff:
        duration: 30s
        maxDuration: 10m
