apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-database
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/soloz-io/zero-ops
    targetRevision: HEAD
    path: manifests/platform-database
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: zero-ops-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 15
      backoff:
        duration: 30s
        maxDuration: 10m
