---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-edge-catalog-applicationset
  namespace: hub-platform-ops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/soloz-io/zero-ops
    targetRevision: HEAD
    path: catalog/argocd
  
  destination:
    server: https://kubernetes.default.svc
    namespace: hub-platform-ops
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
