apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-alerts
  namespace: hub-platform-ops
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: https://github.com/soloz-io/zero-ops
    targetRevision: HEAD
    path: manifests/platform-core-services/victoriametrics-alerts
  destination:
    server: https://kubernetes.default.svc
    namespace: hub-platform-observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
