package bootstrap

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// writeFleetPKIValues records this box's Infisical PKI coordinates in the
// cluster's own values file.
//
// Without them the security boundary renders no ClusterIssuer -- the template
// emits one only when fleet.projectId and fleet.clientId are both supplied --
// and every certificate that names infisical-fleet-issuer stays pending
// forever. On the box this was found on that was eleven certificates: all three
// argocd-agent mTLS identities, and the Support Agent's client certificate,
// which IS its enrolment (ADR-077).
//
// The coordinates were already written -- into the seed Application this CLI
// renders -- and that is the wrong place on a tenant's box. ADR-072 makes the
// tenant's own repository authoritative: when a gitops directory is present the
// cluster is seeded from the repository's bundle.yaml, not from the rendered
// seed, so the parameters went nowhere. Worse, on a box where the seed HAD been
// applied, the root Application reconciles bundle.yaml with selfHeal and strips
// them again within a sync.
//
// So they belong in the declared state, beside every other value the box runs
// on, and they reach the cluster the way everything else does. This is the same
// lesson as the ArgoCD credential and the Infisical secret upload: an imperative
// write against a declarative source is a write that gets reverted.
//
// Absent coordinates are not an error. They mean Infisical has not bootstrapped
// yet, and a later phase re-runs this.
func (o *Orchestrator) writeFleetPKIValues(ctx context.Context, kubeconfig string) error {
	if o.GitopsDir == "" {
		return nil // no tenant repository; the rendered seed carries them
	}
	projectID, clientID := o.infisicalCoordinates(ctx, kubeconfig)
	if projectID == "" || clientID == "" {
		return nil
	}

	// Written to generated/, NOT to the cluster's own values.yaml. That file
	// carries the line "The platform never writes this file", and it means it:
	// it is where a tenant states what they want, and a process that edits it
	// makes every hand-written value something a later run might rewrite.
	// Generated facts live beside the other generated facts, and bundle.yaml
	// reads both.
	// generated/values/, not generated/. The Application that reconciles
	// generated/ applies what it finds there as Kubernetes objects, and this
	// file is a Helm values file consumed through $values -- it has no `kind`,
	// so applying it fails with "Object 'Kind' is missing". Keeping values in
	// their own directory is what makes the two impossible to confuse.
	dir := filepath.Join(o.GitopsDir, "clusters", o.ClusterName, "generated", "values")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("cannot create %s: %w", dir, err)
	}
	path := filepath.Join(dir, "platform-pki-values.yaml")

	block := fmt.Sprintf(`
# This box's own Infisical, and the identity that issues its certificates.
#
# GENERATED BY DAY-0 (ADR-045). Do not edit; it is rewritten on every bootstrap.
#
# Written once Infisical has bootstrapped, because only then do these exist, and
# recorded in the declared state rather than set on the live Application: the
# root Application reconciles this repository with selfHeal, so a value that
# lives only on the cluster is reverted within a sync.
#
# Without them the security boundary emits no ClusterIssuer at all, and every
# certificate naming infisical-fleet-issuer stays pending -- the
# argocd-agent mTLS identities never issue, and the Support Agent can never
# enrol, because its client certificate IS its enrolment (ADR-035, ADR-077).
#
# Both together or neither. The chart refuses one without the other, because an
# issuer built from half of them authenticates as nobody against a project that
# does not exist.
infisical:
  fleet:
    projectId: %q
    clientId: %q
`, projectID, clientID)

	if err := os.WriteFile(path, []byte(strings.TrimLeft(block, "\n")), 0o644); err != nil {
		return fmt.Errorf("cannot record the PKI coordinates in %s: %w", path, err)
	}
	fmt.Printf("[bootstrap-infisical-api] ✓ PKI coordinates recorded in clusters/%s/generated/platform-pki-values.yaml\n",
		o.ClusterName)
	return nil
}
