package bootstrap

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
)

// writeGatewayDNSTarget records the hub's public ingress address where the hub
// Gateway and its routes can be patched with it.
//
// external-dns publishes the hostnames it finds on the Gateway's HTTPRoutes but
// has no address to point them at: in hostNetwork mode the Gateway's generated
// Service is a ClusterIP, so nothing in the cluster carries a routable address.
// The address is the CAPH control-plane load balancer's, known only once that
// load balancer exists, which is why it cannot live in the base manifest.
//
// THIS EXISTED BEFORE AND WAS REMOVED. writeExternalDNSTargetArtifact wrote the
// same value into manifests/hub-core-services/gateway/generated/ and committed
// it -- one cluster's address in the shared component source, inherited by every
// cluster rendering from it, which is why 181f159b deleted it (ADR-062/063). The
// diagnosis was right and the replacement was not: the address became a chart
// value fed from hubIngressAddress, and ADR-072 then made the tenant's own
// repository the seed, where that value is empty. From that point no hub
// hostname resolved on any tenant box.
//
// The old commit judged the empty case benign -- "external-dns then falls back
// to the Gateway's own address, so public DNS is wrong rather than absent" --
// but the kustomization it deleted said in its own comment that the Gateway's
// address is a ClusterIP. external-dns will not publish one. Absent, not wrong,
// and absent is silent: "All records are already up to date" against an empty
// zone, every status green.
//
// So the mechanism returns, pointed at the TENANT's repository rather than the
// platform's. The value is this box's and lives with this box's other Day-0
// facts, beside platform-pki-values.yaml, and ArgoCD reconciles it like anything
// else. No chart reads a ConfigMap, and no operator co-owns a field with ArgoCD.
func (o *Orchestrator) writeGatewayDNSTarget(ctx context.Context, kubeconfig string) error {
	if o.GitopsDir == "" {
		return nil // no tenant repository; nothing to write it into
	}

	address := o.hubIngressAddress(ctx, kubeconfig)
	if address == "" {
		// Not fatal here: this runs early, and the load balancer may not have an
		// address yet. applySeed runs at the start of every boundary phase, so a
		// later pass records it. What must not happen is a WRONG value.
		return nil
	}

	// generated/values/, not generated/. The Application that reconciles
	// generated/ applies what it finds there as Kubernetes objects, and this
	// file is a Helm values file consumed through $values -- it has no `kind`,
	// so applying it fails with "Object 'Kind' is missing". Keeping values in
	// their own directory is what makes the two impossible to confuse.
	dir := filepath.Join(o.GitopsDir, "clusters", o.ClusterName, "generated", "values")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("cannot create %s: %w", dir, err)
	}
	path := filepath.Join(dir, "gateway-dns-target.yaml")

	content := fmt.Sprintf(`# The address every public hostname on this box resolves to.
#
# GENERATED BY DAY-0. Do not edit; it is rewritten on every bootstrap. It is the
# CAPH control-plane load balancer (HetznerCluster.spec.controlPlaneEndpoint.host),
# which also carries public ingress on 80/443 (ADR-046 §25.3).
#
# Read as a chart value rather than patched onto the live objects, so Git stays
# the source of truth and ArgoCD has no field to ignore. The hub Gateway and all
# nine HTTPRoutes take the annotation from it, because external-dns's
# gateway-httproute source reads the target from the ROUTE and only falls back to
# the Gateway -- whose address, in hostNetwork mode, is a ClusterIP it will not
# publish.
#
# A stale value here reaches public DNS and every hub hostname resolves to
# whatever it says, so it is regenerated rather than edited.
hubIngressAddress: %q
`, address)

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("cannot record the gateway DNS target in %s: %w", path, err)
	}
	fmt.Printf("[seed] ✓ hub ingress address %s recorded in clusters/%s/generated/gateway-dns-target.yaml\n",
		address, o.ClusterName)
	return nil
}
