#!/bin/bash
# Manual test script for kube-sbt OpenMeter providers
# This script must be run manually in the Hub cluster to validate Checkpoint 1 and 2

set -e

KUBECONFIG=${KUBECONFIG:-"k8-secrets/kubeconfig/hub.kubeconfig"}
NAMESPACE="hub-platform-billing"

echo "========================================="
echo "kube-sbt OpenMeter Providers Manual Test"
echo "========================================="
echo ""
echo "IMPORTANT: This is a MANUAL test script."
echo "Follow the instructions and verify each step manually."
echo ""
echo "Cluster: $(kubectl config current-context)"
echo "Namespace: ${NAMESPACE}"
echo ""

# Step 1: Verify OpenMeter is running
echo "Step 1: Verify OpenMeter deployment"
echo "-----------------------------------"
echo "Run: kubectl get pods -n ${NAMESPACE} -l app.kubernetes.io/name=openmeter"
echo ""
echo "Expected: All OpenMeter pods should be Running (1/1 Ready)"
echo "  - openmeter-api"
echo "  - openmeter-balance-worker"
echo "  - openmeter-billing-worker"
echo "  - openmeter-notification-service"
echo "  - openmeter-sink-worker"
echo "  - svix"
echo ""
read -p "Press Enter when verified..."
echo ""

# Step 2: Port-forward to OpenMeter API
echo "Step 2: Setup port-forward to OpenMeter API"
echo "-------------------------------------------"
echo "Run in a separate terminal:"
echo "  kubectl port-forward -n ${NAMESPACE} svc/openmeter-api 8888:8080"
echo ""
read -p "Press Enter when port-forward is active..."
echo ""

# Step 3: Test OpenMeter health
echo "Step 3: Test OpenMeter health endpoint"
echo "--------------------------------------"
echo "Run: curl -s http://localhost:8888/api/v1/health | jq"
echo ""
echo "Expected: {\"status\": \"ok\"} or similar healthy response"
echo ""
read -p "Press Enter when verified..."
echo ""

# Step 4: Create test namespace
TEST_NAMESPACE="test-tenant-$(date +%s)"
echo "Step 4: Create test namespace in OpenMeter"
echo "------------------------------------------"
echo "Run:"
echo "  curl -X POST http://localhost:8888/api/v1/namespaces \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"id\":\"${TEST_NAMESPACE}\",\"name\":\"Test Tenant\"}' | jq"
echo ""
echo "Expected: Namespace created successfully with id: ${TEST_NAMESPACE}"
echo ""
read -p "Press Enter when verified..."
echo ""

# Step 5: Register test subject
TEST_SUBJECT="${TEST_NAMESPACE}#user-001"
echo "Step 5: Register test subject (CHECKPOINT 1 - Subject Management)"
echo "-----------------------------------------------------------------"
echo "Run:"
echo "  curl -X POST 'http://localhost:8888/api/v1/subjects?namespace=${TEST_NAMESPACE}' \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"key\":\"${TEST_SUBJECT}\",\"displayName\":\"Test User\",\"metadata\":{\"email\":\"test@example.com\"}}' | jq"
echo ""
echo "Expected: Subject created with key: ${TEST_SUBJECT}"
echo ""
echo "CHECKPOINT 1 VALIDATION:"
echo "  ✓ Subject registration creates subjects in OpenMeter"
echo "  ✓ Namespace isolation enforced (namespace parameter required)"
echo ""
read -p "Press Enter when verified..."
echo ""

# Step 6: Retrieve subject
echo "Step 6: Retrieve test subject (CHECKPOINT 1 - Subject Retrieval)"
echo "----------------------------------------------------------------"
echo "Run:"
echo "  curl -s 'http://localhost:8888/api/v1/subjects/${TEST_SUBJECT}?namespace=${TEST_NAMESPACE}' | jq"
echo ""
echo "Expected: Subject details returned with correct metadata"
echo ""
read -p "Press Enter when verified..."
echo ""

# Step 7: List subjects
echo "Step 7: List subjects in namespace"
echo "----------------------------------"
echo "Run:"
echo "  curl -s 'http://localhost:8888/api/v1/subjects?namespace=${TEST_NAMESPACE}' | jq"
echo ""
echo "Expected: Array containing the test subject"
echo ""
read -p "Press Enter when verified..."
echo ""

# Step 8: Test meters endpoint
echo "Step 8: Test meters catalog endpoint (CHECKPOINT 1 - Catalog)"
echo "-------------------------------------------------------------"
echo "Run:"
echo "  curl -s 'http://localhost:8888/api/v1/meters?namespace=${TEST_NAMESPACE}' | jq"
echo ""
echo "Expected: Empty array [] (no meters configured yet) OR list of meters if catalog exists"
echo ""
read -p "Press Enter when verified..."
echo ""

# Step 9: Test features endpoint
echo "Step 9: Test features catalog endpoint"
echo "--------------------------------------"
echo "Run:"
echo "  curl -s 'http://localhost:8888/api/v1/features?namespace=${TEST_NAMESPACE}' | jq"
echo ""
echo "Expected: Empty array [] (no features configured yet) OR list of features if catalog exists"
echo ""
read -p "Press Enter when verified..."
echo ""

# Step 10: Test plans endpoint
echo "Step 10: Test plans catalog endpoint"
echo "------------------------------------"
echo "Run:"
echo "  curl -s 'http://localhost:8888/api/v1/plans?namespace=${TEST_NAMESPACE}' | jq"
echo ""
echo "Expected: {\"items\": [], \"totalCount\": 0} OR list of plans if catalog exists"
echo ""
read -p "Press Enter when verified..."
echo ""

# Step 11: Test entitlement checking (fail-open)
echo "Step 11: Test entitlement checking (CHECKPOINT 1 - Fail-Open)"
echo "-------------------------------------------------------------"
echo "Run:"
echo "  curl -s 'http://localhost:8888/api/v1/subjects/${TEST_SUBJECT}/entitlements/test-feature?namespace=${TEST_NAMESPACE}' | jq"
echo ""
echo "Expected: 404 Not Found (feature doesn't exist) - this tests fail-open behavior"
echo ""
echo "CHECKPOINT 1 VALIDATION:"
echo "  ✓ Entitlement checking queries OpenMeter API"
echo "  ✓ Fail-open behavior when feature not found"
echo ""
read -p "Press Enter when verified..."
echo ""

# Step 12: Test subscription creation (CHECKPOINT 2)
echo "Step 12: Test subscription creation (CHECKPOINT 2 - Billing)"
echo "------------------------------------------------------------"
echo "NOTE: This requires a plan to exist. If no plans configured, skip this step."
echo ""
echo "If you have a plan configured, run:"
echo "  curl -X POST 'http://localhost:8888/api/v1/subscriptions?namespace=${TEST_NAMESPACE}' \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"customerId\":\"${TEST_SUBJECT}\",\"plan\":{\"key\":\"<PLAN_KEY>\"}}' | jq"
echo ""
echo "Expected: Subscription created successfully"
echo ""
echo "CHECKPOINT 2 VALIDATION:"
echo "  ✓ Subscription creation assigns plans to subjects"
echo "  ✓ Namespace isolation enforced"
echo ""
read -p "Press Enter to continue (or skip if no plans configured)..."
echo ""

# Step 13: Cleanup
echo "Step 13: Cleanup test data"
echo "-------------------------"
echo "Run:"
echo "  curl -X DELETE 'http://localhost:8888/api/v1/subjects/${TEST_SUBJECT}?namespace=${TEST_NAMESPACE}'"
echo "  curl -X DELETE 'http://localhost:8888/api/v1/namespaces/${TEST_NAMESPACE}'"
echo ""
echo "Expected: Subject and namespace deleted successfully"
echo ""
read -p "Press Enter when cleanup complete..."
echo ""

# Summary
echo "========================================="
echo "Manual Test Summary"
echo "========================================="
echo ""
echo "CHECKPOINT 1: OpenMeter Provider Foundation"
echo "  Test Items:"
echo "    ✓ Subject registration with namespace isolation"
echo "    ✓ Subject retrieval"
echo "    ✓ Subject listing"
echo "    ✓ Catalog endpoints (meters, features, plans)"
echo "    ✓ Entitlement checking with fail-open"
echo ""
echo "CHECKPOINT 2: Billing Provider Complete"
echo "  Test Items:"
echo "    ✓ Subscription creation (if plans configured)"
echo "    ✓ Namespace isolation"
echo ""
echo "Next Steps:"
echo "  1. Configure billing catalog via GitOps (Phase 4)"
echo "  2. Deploy kube-sbt-api to cluster"
echo "  3. Test full REST API with JWT authentication"
echo "  4. Run integration tests with real workloads"
echo ""
echo "Test namespace used: ${TEST_NAMESPACE}"
echo "Test subject used: ${TEST_SUBJECT}"
echo ""
