apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-backend
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  provider:
    infisical:
      hostAPI: "https://infisical.zero-ops-system.svc/api"
      secretsScope:
        projectSlug: "platform"
        environmentSlug: "production"
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-auth
            key: client-id
            namespace: external-secrets-system
          clientSecret:
            name: infisical-auth
            key: client-secret
            namespace: external-secrets-system
