apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-ops

resources:
- manager.yaml
- network-policy.yaml
- identity-credentials-es.yaml

images:
- digest: sha256:7074fa6d288cf0dc051e3ebd840e6ce1f4b5d48287f40dc64ebccfc18116a323
  name: controller
  newName: ghcr.io/soloz-io/zero-ops/kube-sbt

labels:
- pairs:
    app.kubernetes.io/component: metering-api
    app.kubernetes.io/name: kube-sbt
    app.kubernetes.io/part-of: kube-sbt
