apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-ops

resources:
- manager.yaml
- network-policy.yaml
- identity-credentials-es.yaml

images:
- digest: sha256:0fd2a37c0fbf22c5ca42d15288cdf6ed30c38c077255968dc976da26d1f5b96b
  name: controller
  newName: ghcr.io/soloz-io/zero-ops/kube-sbt

labels:
- pairs:
    app.kubernetes.io/component: metering-api
    app.kubernetes.io/name: kube-sbt
    app.kubernetes.io/part-of: kube-sbt
