apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-ops

resources:
- manager.yaml
- network-policy.yaml
- identity-credentials-es.yaml

images:
- digest: sha256:7235ea48e0e63dde52ff0c7fb81a2eedc82d64948dee8f54720fd45f61120ba9
  name: controller
  newName: ghcr.io/soloz-io/zero-ops/kube-sbt

labels:
- pairs:
    app.kubernetes.io/component: metering-api
    app.kubernetes.io/name: kube-sbt
    app.kubernetes.io/part-of: kube-sbt
