apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infisical-issuer-crd.yaml
  - infisical-issuer.yaml
  - infisical-fleet-issuer.yaml
  - cert-manager-approve-infisical-issuer.yaml

patches:
  - path: generated/infisical-fleet-issuer-patch.yaml
