nameReference:
  - kind: ServiceAccount
    version: v1
    fieldSpecs:
      - kind: Rollout
        group: argoproj.io
        path: spec/template/spec/serviceAccountName

commonLabels:
  - path: spec/selector/matchLabels
    kind: Rollout
    group: argoproj.io
    version: v1alpha1
    create: true
  - path: spec/template/metadata/labels
    kind: Rollout
    group: argoproj.io
    version: v1alpha1
    create: true
  - path: spec/endpointSelector/matchLabels
    kind: CiliumNetworkPolicy
    group: cilium.io
    version: v2
    create: true

images:
  - path: spec/template/spec/containers/image
    kind: Rollout
    group: argoproj.io
    version: v1alpha1
