{{ if .Values.deploy.boundary02 }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 02-platform-data-multi
  namespace: platform-ops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - list:
        elements: []
  template:
    metadata:
      name: '{{"{{"}} .appName {{"}}"}}'
      namespace: platform-ops
      annotations:
        argocd.argoproj.io/sync-wave: '{{"{{"}} .syncWave {{"}}"}}'
    spec:
      project: default
      sources:
        - repoURL: '{{"{{"}} .repoURL {{"}}"}}'
          chart: '{{"{{"}} .chart {{"}}"}}'
          targetRevision: '{{"{{"}} .targetRevision {{"}}"}}'
          helm:
            releaseName: '{{"{{"}} .helmReleaseName {{"}}"}}'
            valueFiles:
              - $values/{{"{{"}} .valueFilesPath {{"}}"}}
        - repoURL: https://github.com/soloz-io/zero-ops
          targetRevision: '{{ .Values.environmentRevision }}'
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{"{{"}} .destinationNamespace {{"}}"}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
---
{{ end }}
