apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 03-platform-services
  namespace: platform-ops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - list:
        elements:
          - appName: 'api-gateway'
            destinationNamespace: 'platform-controlplane'
            isPlatformOwned: 'true'
            syncWave: ''
            repoURL: 'https://github.com/soloz-io/zero-ops'
            targetRevision: ''
            path: 'manifests/hub-core-services/api-gateway'
            chart: ''
            directoryRecurse: ''
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: ''
          - appName: 'cert-operator'
            destinationNamespace: 'platform-ops'
            isPlatformOwned: 'true'
            syncWave: '3'
            repoURL: 'https://github.com/soloz-io/zero-ops'
            targetRevision: ''
            path: 'operators/cert-operator/config/default'
            chart: ''
            directoryRecurse: ''
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: ''
          - appName: 'clickhouse-operator'
            destinationNamespace: 'platform-ops'
            isPlatformOwned: 'false'
            syncWave: ''
            repoURL: 'https://helm.altinity.com'
            targetRevision: '0.26.3'
            path: ''
            chart: 'altinity-clickhouse-operator'
            directoryRecurse: ''
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: 'clickhouse-operator'
          - appName: 'platform-argocd-fleet-registry-auth'
            destinationNamespace: 'platform-ops'
            isPlatformOwned: 'true'
            syncWave: ''
            repoURL: 'https://github.com/soloz-io/zero-ops'
            targetRevision: ''
            path: 'manifests/hub-core-services/argocd-fleet-registry-auth'
            chart: ''
            directoryRecurse: 'true'
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: ''
          - appName: 'platform-argocd-github-auth'
            destinationNamespace: 'platform-ops'
            isPlatformOwned: 'true'
            syncWave: ''
            repoURL: 'https://github.com/soloz-io/zero-ops'
            targetRevision: ''
            path: 'manifests/hub-core-services/argocd-github-auth'
            chart: ''
            directoryRecurse: 'true'
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: ''
          - appName: 'platform-capi2argo'
            destinationNamespace: 'platform-ops'
            isPlatformOwned: 'true'
            syncWave: ''
            repoURL: 'https://github.com/soloz-io/zero-ops'
            targetRevision: ''
            path: 'manifests/hub-core-services/capi2argo'
            chart: ''
            directoryRecurse: ''
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: ''
          - appName: 'hub-environment'
            destinationNamespace: 'platform-ops'
            isPlatformOwned: 'true'
            syncWave: ''
            repoURL: 'https://github.com/soloz-io/zero-ops'
            targetRevision: ''
            path: 'manifests/environments/{{ .Values.environmentSlug }}'
            chart: ''
            directoryRecurse: ''
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: ''
          - appName: 'infrastructure-provider'
            destinationNamespace: 'platform-ops'
            isPlatformOwned: 'true'
            syncWave: '2'
            repoURL: 'https://github.com/soloz-io/zero-ops'
            targetRevision: ''
            path: 'manifests/providers/{{ .Values.provider }}'
            chart: ''
            directoryRecurse: 'false'
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: ''
          - appName: 'grafana-alloy'
            destinationNamespace: 'platform-observability'
            isPlatformOwned: 'false'
            syncWave: ''
            repoURL: 'https://github.com/soloz-io/zero-ops.git'
            targetRevision: 'main'
            path: 'manifests/hub-core-services/grafana-alloy'
            chart: ''
            directoryRecurse: ''
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: ''
          - appName: 'platform-identity'
            destinationNamespace: 'platform-ops'
            isPlatformOwned: 'true'
            syncWave: ''
            repoURL: 'https://github.com/soloz-io/zero-ops'
            targetRevision: ''
            path: 'manifests/hub-core-services/identity/argocd'
            chart: ''
            directoryRecurse: ''
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: ''
          - appName: 'platform-infisical-prerequisites'
            destinationNamespace: 'platform-security'
            isPlatformOwned: 'true'
            syncWave: ''
            repoURL: 'https://github.com/soloz-io/zero-ops'
            targetRevision: ''
            path: 'manifests/hub-core-services/infisical'
            chart: ''
            directoryRecurse: 'true'
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: ''

          - appName: 'hub-operator'
            destinationNamespace: 'platform-ops'
            isPlatformOwned: 'true'
            syncWave: ''
            repoURL: 'https://github.com/soloz-io/zero-ops'
            targetRevision: ''
            path: 'operators/hub-operator/config/default'
            chart: ''
            directoryRecurse: ''
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: ''
          - appName: 'prometheus-operator'
            destinationNamespace: 'platform-observability'
            isPlatformOwned: 'false'
            syncWave: ''
            repoURL: 'https://prometheus-community.github.io/helm-charts'
            targetRevision: '82.15.0'
            path: ''
            chart: 'kube-prometheus-stack'
            directoryRecurse: ''
            directoryInclude: ''
            helmValues: |
              prometheus:
                enabled: false
              alertmanager:
                enabled: false
              grafana:
                enabled: false
              prometheusOperator:
                enabled: true
              kubeStateMetrics:
                enabled: false
              nodeExporter:
                enabled: false
            helmReleaseName: ''
          - appName: 'platform-spire'
            destinationNamespace: 'platform-security'
            isPlatformOwned: 'true'
            syncWave: ''
            repoURL: 'https://github.com/soloz-io/zero-ops'
            targetRevision: ''
            path: 'manifests/hub-core-services/spire'
            chart: ''
            directoryRecurse: ''
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: ''
          - appName: 'victoria-metrics-alerts'
            destinationNamespace: 'platform-observability'
            isPlatformOwned: 'true'
            syncWave: ''
            repoURL: 'https://github.com/soloz-io/zero-ops'
            targetRevision: ''
            path: 'manifests/hub-core-services/victoriametrics-alerts'
            chart: ''
            directoryRecurse: ''
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: ''
          - appName: 'platform-victoriametrics-infisical'
            destinationNamespace: 'platform-observability'
            isPlatformOwned: 'true'
            syncWave: ''
            repoURL: 'https://github.com/soloz-io/zero-ops'
            targetRevision: ''
            path: 'manifests/hub-core-services/victoriametrics'
            chart: ''
            directoryRecurse: 'true'
            directoryInclude: 'infisical-integration.yaml'
            helmValues: ''
            helmReleaseName: ''
          - appName: 'victoriametrics-ingress'
            destinationNamespace: 'platform-observability'
            isPlatformOwned: 'false'
            syncWave: ''
            repoURL: 'https://github.com/soloz-io/zero-ops.git'
            targetRevision: 'main'
            path: 'manifests/hub-core-services/victoriametrics'
            chart: ''
            directoryRecurse: 'true'
            directoryInclude: 'ingress.yaml'
            helmValues: ''
            helmReleaseName: ''
          - appName: 'victoria-metrics-operator'
            destinationNamespace: 'platform-observability'
            isPlatformOwned: 'false'
            syncWave: ''
            repoURL: 'https://victoriametrics.github.io/helm-charts'
            targetRevision: '0.59.3'
            path: ''
            chart: 'victoria-metrics-operator'
            directoryRecurse: ''
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: ''
          - appName: 'victoria-metrics-cluster'
            destinationNamespace: 'platform-observability'
            isPlatformOwned: 'false'
            syncWave: ''
            repoURL: 'https://victoriametrics.github.io/helm-charts'
            targetRevision: '0.37.0'
            path: ''
            chart: 'victoria-metrics-cluster'
            directoryRecurse: ''
            directoryInclude: ''
            helmValues: |
              vmselect:
                replicaCount: 1
                resources:
                  requests:
                    cpu: 250m
                    memory: 256Mi
                  limits:
                    cpu: 1000m
                    memory: 2Gi
              vminsert:
                replicaCount: 1
                resources:
                  requests:
                    cpu: 250m
                    memory: 256Mi
                  limits:
                    cpu: 1000m
                    memory: 2Gi
              vmstorage:
                replicaCount: 1
                persistentVolume:
                  enabled: true
                  size: 50Gi
                resources:
                  requests:
                    cpu: 500m
                    memory: 512Mi
                  limits:
                    cpu: 2000m
                    memory: 4Gi
              retentionPeriod: 30d
            helmReleaseName: ''
          - appName: 'kube-sbt-api'
            destinationNamespace: 'platform-ops'
            isPlatformOwned: 'true'
            syncWave: ''
            repoURL: 'https://github.com/soloz-io/zero-ops.git'
            targetRevision: ''
            path: 'manifests/hub-core-services/kube-sbt-api'
            chart: ''
            directoryRecurse: ''
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: ''
          - appName: 'network-policies'
            destinationNamespace: 'platform-ops'
            isPlatformOwned: 'true'
            syncWave: ''
            repoURL: 'https://github.com/soloz-io/zero-ops'
            targetRevision: ''
            path: 'manifests/hub-core-services/identity'
            chart: ''
            directoryRecurse: 'true'
            directoryInclude: 'network-policies.yaml'
            helmValues: ''
            helmReleaseName: ''
          - appName: 'openmeter-secrets'
            destinationNamespace: 'platform-billing'
            isPlatformOwned: 'true'
            syncWave: ''
            repoURL: 'https://github.com/soloz-io/zero-ops'
            targetRevision: ''
            path: 'manifests/hub-core-services/openmeter/secrets'
            chart: ''
            directoryRecurse: 'true'
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: ''
          - appName: 'openmeter'
            destinationNamespace: 'platform-billing'
            isPlatformOwned: 'true'
            syncWave: ''
            repoURL: 'https://github.com/soloz-io/zero-ops.git'
            targetRevision: ''
            path: 'manifests/hub-core-services/openmeter'
            chart: ''
            directoryRecurse: ''
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: ''
          - appName: 'platform-spoke-bootstrap-templates'
            destinationNamespace: 'platform-capi'
            isPlatformOwned: 'true'
            syncWave: '1'
            repoURL: 'https://github.com/soloz-io/zero-ops.git'
            targetRevision: ''
            path: 'manifests/spoke/spoke-bootstrap'
            chart: ''
            directoryRecurse: 'true'
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: ''
          - appName: 'platform-spoke-pool-xrds'
            destinationNamespace: 'default'
            isPlatformOwned: 'true'
            syncWave: '1'
            repoURL: 'https://github.com/soloz-io/zero-ops'
            targetRevision: ''
            path: 'manifests/spoke/xrds'
            chart: ''
            directoryRecurse: ''
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: ''
          - appName: 'platform-spoke-pools'
            destinationNamespace: 'platform-ops'
            isPlatformOwned: 'true'
            syncWave: '10'
            repoURL: 'https://github.com/soloz-io/zero-ops'
            targetRevision: ''
            path: 'manifests/spoke/spoke-pools/{{ .Values.environmentSlug }}/{{ .Values.provider }}'
            chart: ''
            directoryRecurse: 'true'
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: ''
          - appName: 'platform-tenant-platform'
            destinationNamespace: 'default'
            isPlatformOwned: 'true'
            syncWave: '5'
            repoURL: 'https://github.com/soloz-io/zero-ops'
            targetRevision: ''
            path: 'manifests/hub-core-services/crossplane/tenant-platform'
            chart: ''
            directoryRecurse: 'true'
            directoryInclude: ''
            helmValues: ''
            helmReleaseName: ''
  template:
    metadata:
      name: '{{"{{"}} .appName {{"}}"}}'
      namespace: platform-ops
      annotations:
        argocd.argoproj.io/sync-wave: '{{"{{"}} .syncWave {{"}}"}}'
    spec:
      project: default
      source:
        repoURL: '{{"{{"}} .repoURL {{"}}"}}'
        targetRevision: '{{"{{"}} if eq .isPlatformOwned "true" {{"}}"}}{{ .Values.environmentRevision }}{{"{{"}} else {{"}}"}}{{"{{"}} .targetRevision {{"}}"}}{{"{{"}} end {{"}}"}}'
        path: '{{"{{"}} .path {{"}}"}}'
        chart: '{{"{{"}} .chart {{"}}"}}'
        helm:
          releaseName: '{{"{{"}} .helmReleaseName {{"}}"}}'
          values: '{{"{{"}} .helmValues {{"}}"}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{"{{"}} .destinationNamespace {{"}}"}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
  templatePatch: |
    {{"{{-"}} if .path {{"}}"}}
    spec:
      source:
        directory:
          recurse: {{"{{"}} eq .directoryRecurse "true" {{"}}"}}
    {{"{{-"}} end {{"}}"}}
    {{"{{-"}} if eq .appName "hub-environment" {{"}}"}}
    spec:
      ignoreDifferences:
      - kind: ConfigMap
        name: hub-bootstrap-config
        jsonPointers:
        - /data/INFISICAL_BOOTSTRAP_PROFILE_SLUG
        - /data/INFISICAL_ORGANIZATION_ID
        - /data/INFISICAL_PROJECT_ID
    {{"{{-"}} end {{"}}"}}
