apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hetzner-dns-credentials
  namespace: platform-edge
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: infisical-backend
    kind: ClusterSecretStore

  target:
    name: hetzner-dns
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        api-key: "{{ .apikey }}"

  data:
    - secretKey: apikey
      remoteRef:
        key: hcloud-token
