---
apiVersion: nutgraf.in/v1alpha1
kind: SpokePool
metadata:
  name: local-dev
  namespace: platform-ops
  labels:
    spoke-type: pool
    environment: local
spec:
  provider: local
  providerConfigRef:
    name: mac-cluster-engine
  compositionSelector:
    matchLabels:
      provider: docker
  region: local
  nodePool:
    count: 1
    instanceType: capd
  maxTenantCapacity: 5
