apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-echo
  namespace: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-echo
  template:
    metadata:
      labels:
        app: demo-echo
    spec:
      containers:
        - name: echo
          image: ealen/echo-server:latest
          ports:
            - containerPort: 8080
