apiVersion: v1
kind: Secret
metadata:
  name: nats-auth
  namespace: zero-ops-system
type: Opaque
stringData:
  agent-password: "" # TODO: Generate via Infisical
  spoke-password: "" # TODO: Generate via Infisical