appName: platform-external-secrets
destinationNamespace: platform-ops
isPlatformOwned: false
targetRevision: 2.2.0
repoURL: https://charts.external-secrets.io
chart: external-secrets
helmValues: "installCRDs: false\n\ncrds:\n  createClusterExternalSecret: true\n  createClusterSecretStore:\
  \ true\n  createSecretStore: true\n  createClusterGenerator: true\n  createClusterPushSecret:\
  \ true\n  createPushSecret: true\n\nreplicaCount: 1\n\nprocessClusterPushSecret:\
  \ true\nprocessPushSecret: true\n\nimage:\n  repository: ghcr.io/external-secrets/external-secrets\n\
  \  tag: \"v2.2.0\"\n  pullPolicy: IfNotPresent\n\nresources:\n  requests:\n    cpu:\
  \ 10m\n    memory: 64Mi\n  limits:\n    memory: 128Mi\n\nprocessClusterExternalSecret:\
  \ true\nprocessClusterStore: true\nprocessSecretStore: true\n\nmetrics:\n  service:\n\
  \    enabled: true\n    port: 8080\n\nserviceMonitor:\n  enabled: true\n  interval:\
  \ 30s\n\nsecurityContext:\n  enabled: true\n  runAsNonRoot: true\n  runAsUser: 1000\n\
  \  readOnlyRootFilesystem: true\n"
syncWave: '4'
syncOptions:
- CreateNamespace=true
- ServerSideApply=true
- RespectIgnoreDifferences=true
retryLimit: 15
retryDuration: 30s
retryMaxDuration: 10m
