appName: platform-cluster-secret-store
destinationNamespace: platform-ops
isPlatformOwned: true
repoURL: https://github.com/soloz-io/zero-ops
path: manifests/hub-core-services/cluster-secret-store
directoryRecurse: true
syncWave: '5'
retryLimit: 15
retryDuration: 30s
retryMaxDuration: 10m
