appName: platform-crossplane-config
destinationNamespace: platform-ops
isPlatformOwned: true
repoURL: https://github.com/soloz-io/zero-ops
path: manifests/hub-core-services/crossplane/config
syncWave: '4'
syncOptions:
- SkipDryRunOnMissingResource=true
retryLimit: 5
retryDuration: 5s
retryMaxDuration: 3m
