appName: ingress-config
destinationNamespace: platform-ops
isPlatformOwned: true
repoURL: https://github.com/soloz-io/zero-ops
path: manifests/hub-core-services/ingress
directoryRecurse: false
directoryInclude: '{cluster-issuer.yaml,ingress.yaml}'
syncOptions:
- ServerSideApply=true
retryLimit: 15
retryDuration: 30s
retryMaxDuration: 10m
