apiVersion: v1
kind: ConfigMap
metadata:
  name: hub-bootstrap-config
  namespace: platform-ops
data:
  CLUSTER_ID: "hub-dev"
  INFISICAL_ENVIRONMENT_SLUG: "dev"
  INFISICAL_PROJECT_SLUG: "hub-platform"
  INFISICAL_SECRETS_PROJECT_SLUG: "hub-secrets"
  CLUSTER_REGION: ""
