// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Tenant struct {
	ID        pgtype.UUID      `json:"id"`
	OrgID     pgtype.UUID      `json:"org_id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Plan      string           `json:"plan"`
	Status    string           `json:"status"`
	Quotas    []byte           `json:"quotas"`
	Metadata  []byte           `json:"metadata"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}
