// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountTenants(ctx context.Context, arg CountTenantsParams) (int64, error)
	GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error)
	SoftDeleteTenant(ctx context.Context, id pgtype.UUID) error
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpsertTenant(ctx context.Context, arg UpsertTenantParams) (UpsertTenantRow, error)
}

var _ Querier = (*Queries)(nil)
