apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: hetzner-mgmt-flatcar-v1
  namespace: zero-ops-system
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: hetzner-mgmt-control-plane
    machineInfrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: hetzner-mgmt-control-plane-machine
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: HetznerClusterTemplate
      name: hetzner-mgmt-cluster
  workers:
    machineDeployments:
    - class: default-worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: KubeadmConfigTemplate
            name: hetzner-mgmt-worker-bootstrap
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: HCloudMachineTemplate
            name: hetzner-mgmt-worker-machine
  variables:
  - name: region
    required: true
    schema:
      openAPIV3Schema:
        type: string
        default: fsn1
  - name: imageId
    required: true
    schema:
      openAPIV3Schema:
        type: string
        default: flatcar-stable
  - name: hcloudControlPlaneMachineType
    required: false
    schema:
      openAPIV3Schema:
        type: string
        default: cpx31
  - name: hcloudWorkerMachineType
    required: false
    schema:
      openAPIV3Schema:
        type: string
        default: cpx31
  - name: hcloudNetwork
    required: false
    schema:
      openAPIV3Schema:
        type: object
        properties:
          enabled:
            type: boolean
          cidrBlock:
            type: string
          subnetCidrBlock:
            type: string
          networkZone:
            type: string
  patches:
  - name: region
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HetznerClusterTemplate
        matchResources:
          infrastructureCluster: true
      jsonPatches:
      - op: add
        path: /spec/template/spec/controlPlaneRegions
        valueFrom:
          template: "[{{ .region | quote }}]"
      - op: add
        path: /spec/template/spec/controlPlaneLoadBalancer/region
        valueFrom:
          variable: region
  - name: imageControlPlane
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: replace
        path: /spec/template/spec/imageName
        valueFrom:
          variable: imageId
  - name: imageWorker
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        matchResources:
          machineDeploymentClass:
            names: ["default-worker"]
      jsonPatches:
      - op: replace
        path: /spec/template/spec/imageName
        valueFrom:
          variable: imageId
  - name: controlPlaneMachineType
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: replace
        path: /spec/template/spec/type
        valueFrom:
          variable: hcloudControlPlaneMachineType
  - name: workerMachineType
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        matchResources:
          machineDeploymentClass:
            names: ["default-worker"]
      jsonPatches:
      - op: replace
        path: /spec/template/spec/type
        valueFrom:
          variable: hcloudWorkerMachineType
  - name: hcloudNetwork
    enabledIf: "{{ if .hcloudNetwork.enabled }}true{{end}}"
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HetznerClusterTemplate
        matchResources:
          infrastructureCluster: true
      jsonPatches:
      - op: replace
        path: /spec/template/spec/hcloudNetwork
        valueFrom:
          variable: hcloudNetwork
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerClusterTemplate
metadata:
  name: hetzner-mgmt-cluster
  namespace: zero-ops-system
spec:
  template:
    spec:
      controlPlaneEndpoint:
        host: ""
        port: 443
      controlPlaneLoadBalancer:
        enabled: true
        type: lb11
        region: fsn1
      controlPlaneRegions: []
      hcloudNetwork:
        enabled: true
        cidrBlock: "10.0.0.0/16"
        networkZone: eu-central
      hetznerSecretRef:
        name: hetzner-credentials
        key:
          hcloudToken: hcloud
      sshKeys:
        hcloud: []
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlaneTemplate
metadata:
  name: hetzner-mgmt-control-plane
  namespace: zero-ops-system
spec:
  template:
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          apiServer:
            extraArgs:
              cloud-provider: external
          controllerManager:
            extraArgs:
              cloud-provider: external
          etcd:
            local:
              dataDir: /var/lib/etcd
        initConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cloud-provider: external
        joinConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cloud-provider: external
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: hetzner-mgmt-control-plane-machine
  namespace: zero-ops-system
spec:
  template:
    spec:
      type: cx23
      imageName: flatcar-stable
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: hetzner-mgmt-worker-bootstrap
  namespace: zero-ops-system
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: hetzner-mgmt-worker-machine
  namespace: zero-ops-system
spec:
  template:
    spec:
      type: cx23
      imageName: flatcar-stable
