apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: hetzner-mgmt-ubuntu-v1
  namespace: hub-capi-system
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: hetzner-mgmt-control-plane
    machineInfrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: hetzner-mgmt-ubuntu-control-plane-machine
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: HetznerClusterTemplate
      name: hetzner-mgmt-ubuntu-cluster
  workers:
    machineDeployments:
    - class: default-worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: KubeadmConfigTemplate
            name: hetzner-mgmt-worker-bootstrap
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: HCloudMachineTemplate
            name: hetzner-mgmt-ubuntu-worker-machine
  variables:
  - name: region
    required: true
    schema:
      openAPIV3Schema:
        type: string
        default: fsn1
  - name: imageId
    required: true
    schema:
      openAPIV3Schema:
        type: string
        default: ubuntu-24.04
  - name: hcloudControlPlaneMachineType
    required: false
    schema:
      openAPIV3Schema:
        type: string
        default: cpx31
  - name: hcloudWorkerMachineType
    required: false
    schema:
      openAPIV3Schema:
        type: string
        default: cpx31
  - name: hcloudNetwork
    required: false
    schema:
      openAPIV3Schema:
        type: object
        properties:
          enabled:
            type: boolean
          cidrBlock:
            type: string
          subnetCidrBlock:
            type: string
          networkZone:
            type: string
  patches:
  - name: region
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HetznerClusterTemplate
        matchResources:
          infrastructureCluster: true
      jsonPatches:
      - op: add
        path: /spec/template/spec/controlPlaneRegions
        valueFrom:
          template: "[{{ .region | quote }}]"
      - op: add
        path: /spec/template/spec/controlPlaneLoadBalancer/region
        valueFrom:
          variable: region
  - name: imageControlPlane
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: replace
        path: /spec/template/spec/imageName
        valueFrom:
          variable: imageId
  - name: imageWorker
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        matchResources:
          machineDeploymentClass:
            names: ["default-worker"]
      jsonPatches:
      - op: replace
        path: /spec/template/spec/imageName
        valueFrom:
          variable: imageId
  - name: controlPlaneMachineType
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        matchResources:
          controlPlane: true
      jsonPatches:
      - op: replace
        path: /spec/template/spec/type
        valueFrom:
          variable: hcloudControlPlaneMachineType
  - name: workerMachineType
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        matchResources:
          machineDeploymentClass:
            names: ["default-worker"]
      jsonPatches:
      - op: replace
        path: /spec/template/spec/type
        valueFrom:
          variable: hcloudWorkerMachineType
  - name: hcloudNetwork
    enabledIf: "{{ if .hcloudNetwork.enabled }}true{{end}}"
    definitions:
    - selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HetznerClusterTemplate
        matchResources:
          infrastructureCluster: true
      jsonPatches:
      - op: replace
        path: /spec/template/spec/hcloudNetwork
        valueFrom:
          variable: hcloudNetwork
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HetznerClusterTemplate
metadata:
  name: hetzner-mgmt-ubuntu-cluster
  namespace: hub-capi-system
spec:
  template:
    spec:
      controlPlaneEndpoint:
        host: ""
        port: 443
      controlPlaneLoadBalancer:
        enabled: true
        type: lb11
        region: fsn1
      controlPlaneRegions: []
      hcloudNetwork:
        enabled: true
        cidrBlock: "10.0.0.0/16"
        networkZone: eu-central
      hetznerSecretRef:
        name: hetzner-credentials
        key:
          hcloudToken: hcloud
          hetznerRobotUser: hetzner-robot-user
          hetznerRobotPassword: hetzner-robot-password
          sshKey: hcloud-ssh-key-name
      sshKeys:
        hcloud:
          - name: zero-ops-mac-mini-debug
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlaneTemplate
metadata:
  name: hetzner-mgmt-control-plane
  namespace: hub-capi-system
spec:
  template:
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          apiServer:
            extraArgs:
              cloud-provider: external
          controllerManager:
            extraArgs:
              cloud-provider: external
          etcd:
            local:
              dataDir: /var/lib/etcd
        initConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cloud-provider: external
              max-pods: "120"
              resolv-conf: /etc/kubernetes/resolv.conf
        joinConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cloud-provider: external
              max-pods: "120"
              resolv-conf: /etc/kubernetes/resolv.conf
        files:
          - path: /etc/sysctl.d/99-cilium.conf
            owner: "root:root"
            permissions: "0744"
            content: |
              net.ipv4.conf.lxc*.rp_filter = 0
          - path: /etc/modules-load.d/crio.conf
            owner: "root:root"
            permissions: "0744"
            content: |
              overlay
              br_netfilter
          - path: /etc/sysctl.d/99-kubernetes-cri.conf
            owner: "root:root"
            permissions: "0744"
            content: |
              net.bridge.bridge-nf-call-iptables  = 1
              net.bridge.bridge-nf-call-ip6tables = 1
              net.ipv4.ip_forward                 = 1
          - path: /etc/sysctl.d/99-kubelet.conf
            owner: "root:root"
            permissions: "0744"
            content: |
              vm.overcommit_memory=1
              kernel.panic=10
              kernel.panic_on_oops=1
          - path: /etc/kubernetes/resolv.conf
            owner: "root:root"
            permissions: "0744"
            content: |
              nameserver 1.1.1.1
              nameserver 1.0.0.1
              nameserver 2606:4700:4700::1111
          - content: |
              [Unit]
              Description=containerd container runtime
              Documentation=https://containerd.io
              After=network.target local-fs.target dbus.service

              [Service]
              ExecStartPre=-/sbin/modprobe overlay
              ExecStart=/usr/local/bin/containerd

              Type=notify
              Delegate=yes
              KillMode=process
              Restart=always
              RestartSec=5

              LimitNPROC=infinity
              LimitCORE=infinity
              TasksMax=infinity
              OOMScoreAdjust=-999

              [Install]
              WantedBy=multi-user.target
            owner: root:root
            path: /etc/systemd/system/containerd.service
            permissions: "0744"
        preKubeadmCommands:
          - set -x
          - export CONTAINERD=1.7.26
          - export RUNC=1.2.5
          - export KUBERNETES_VERSION=1.31.6
          - export TRIMMED_KUBERNETES_VERSION=1.31
          - ARCH="$(dpkg --print-architecture)"
          - localectl set-locale LANG=en_US.UTF-8
          - localectl set-locale LANGUAGE=en_US.UTF-8
          - apt-get update -y
          - apt-get -y install at jq unzip wget socat mtr logrotate apt-transport-https
          - sed -i '/swap/d' /etc/fstab
          - swapoff -a
          - modprobe overlay && modprobe br_netfilter && sysctl --system
          - wget https://github.com/opencontainers/runc/releases/download/v$RUNC/runc.$ARCH
          - wget https://github.com/opencontainers/runc/releases/download/v$RUNC/runc.sha256sum
          - sha256sum --check --ignore-missing runc.sha256sum
          - install runc.$ARCH /usr/local/sbin/runc
          - rm -f runc.$ARCH runc.sha256sum
          - wget https://github.com/containerd/containerd/releases/download/v$CONTAINERD/containerd-$CONTAINERD-linux-$ARCH.tar.gz
          - wget https://github.com/containerd/containerd/releases/download/v$CONTAINERD/containerd-$CONTAINERD-linux-$ARCH.tar.gz.sha256sum
          - sha256sum --check containerd-$CONTAINERD-linux-$ARCH.tar.gz.sha256sum
          - tar -zxf containerd-$CONTAINERD-linux-$ARCH.tar.gz -C /usr/local
          - rm -f containerd-$CONTAINERD-linux-$ARCH.tar.gz containerd-$CONTAINERD-linux-$ARCH.tar.gz.sha256sum
          - mkdir -p /etc/containerd
          - containerd config default > /etc/containerd/config.toml
          - sed -i "s/SystemdCgroup = false/SystemdCgroup = true/" /etc/containerd/config.toml
          - systemctl daemon-reload && systemctl enable containerd && systemctl start containerd
          - mkdir -p /etc/apt/keyrings/
          - curl -fsSL https://pkgs.k8s.io/core:/stable:/v$TRIMMED_KUBERNETES_VERSION/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
          - echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v$TRIMMED_KUBERNETES_VERSION/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          - apt-get update
          - apt-get install -y kubelet="$KUBERNETES_VERSION-*" kubeadm="$KUBERNETES_VERSION-*" kubectl="$KUBERNETES_VERSION-*" bash-completion && apt-mark hold kubelet kubectl kubeadm && systemctl enable kubelet
          - kubeadm config images pull --kubernetes-version $KUBERNETES_VERSION
          - echo 'source <(kubectl completion bash)' >>/root/.bashrc
          - echo 'export KUBECONFIG=/etc/kubernetes/admin.conf' >>/root/.bashrc
          - apt-get -y autoremove && apt-get -y clean all
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: hetzner-mgmt-ubuntu-control-plane-machine
  namespace: hub-capi-system
spec:
  template:
    spec:
      type: cx23
      imageName: ubuntu-24.04
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: hetzner-mgmt-worker-bootstrap
  namespace: hub-capi-system
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            max-pods: "220"
            resolv-conf: /etc/kubernetes/resolv.conf
      files:
        - path: /etc/sysctl.d/99-cilium.conf
          owner: "root:root"
          permissions: "0744"
          content: |
            net.ipv4.conf.lxc*.rp_filter = 0
        - path: /etc/modules-load.d/crio.conf
          owner: "root:root"
          permissions: "0744"
          content: |
            overlay
            br_netfilter
        - path: /etc/sysctl.d/99-kubernetes-cri.conf
          owner: "root:root"
          permissions: "0744"
          content: |
            net.bridge.bridge-nf-call-iptables  = 1
            net.bridge.bridge-nf-call-ip6tables = 1
            net.ipv4.ip_forward                 = 1
        - path: /etc/sysctl.d/99-kubelet.conf
          owner: "root:root"
          permissions: "0744"
          content: |
            vm.overcommit_memory=1
            kernel.panic=10
            kernel.panic_on_oops=1
        - path: /etc/kubernetes/resolv.conf
          owner: "root:root"
          permissions: "0744"
          content: |
            nameserver 1.1.1.1
            nameserver 1.0.0.1
            nameserver 2606:4700:4700::1111
        - content: |
            [Unit]
            Description=containerd container runtime
            Documentation=https://containerd.io
            After=network.target local-fs.target dbus.service

            [Service]
            ExecStartPre=-/sbin/modprobe overlay
            ExecStart=/usr/local/bin/containerd

            Type=notify
            Delegate=yes
            KillMode=process
            Restart=always
            RestartSec=5

            LimitNPROC=infinity
            LimitCORE=infinity
            TasksMax=infinity
            OOMScoreAdjust=-999

            [Install]
            WantedBy=multi-user.target
          owner: root:root
          path: /etc/systemd/system/containerd.service
          permissions: "0744"
      preKubeadmCommands:
        - set -x
        - export CONTAINERD=1.7.26
        - export RUNC=1.2.5
        - export KUBERNETES_VERSION=1.31.6
        - export TRIMMED_KUBERNETES_VERSION=1.31
        - ARCH="$(dpkg --print-architecture)"
        - localectl set-locale LANG=en_US.UTF-8
        - localectl set-locale LANGUAGE=en_US.UTF-8
        - apt-get update -y
        - apt-get -y install at jq unzip wget socat mtr logrotate apt-transport-https
        - sed -i '/swap/d' /etc/fstab
        - swapoff -a
        - modprobe overlay && modprobe br_netfilter && sysctl --system
        - wget https://github.com/opencontainers/runc/releases/download/v$RUNC/runc.$ARCH
        - wget https://github.com/opencontainers/runc/releases/download/v$RUNC/runc.sha256sum
        - sha256sum --check --ignore-missing runc.sha256sum
        - install runc.$ARCH /usr/local/sbin/runc
        - rm -f runc.$ARCH runc.sha256sum
        - wget https://github.com/containerd/containerd/releases/download/v$CONTAINERD/containerd-$CONTAINERD-linux-$ARCH.tar.gz
        - wget https://github.com/containerd/containerd/releases/download/v$CONTAINERD/containerd-$CONTAINERD-linux-$ARCH.tar.gz.sha256sum
        - sha256sum --check containerd-$CONTAINERD-linux-$ARCH.tar.gz.sha256sum
        - tar -zxf containerd-$CONTAINERD-linux-$ARCH.tar.gz -C /usr/local
        - rm -f containerd-$CONTAINERD-linux-$ARCH.tar.gz containerd-$CONTAINERD-linux-$ARCH.tar.gz.sha256sum
        - mkdir -p /etc/containerd
        - containerd config default > /etc/containerd/config.toml
        - sed -i "s/SystemdCgroup = false/SystemdCgroup = true/" /etc/containerd/config.toml
        - systemctl daemon-reload && systemctl enable containerd && systemctl start containerd
        - mkdir -p /etc/apt/keyrings/
        - curl -fsSL https://pkgs.k8s.io/core:/stable:/v$TRIMMED_KUBERNETES_VERSION/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        - echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v$TRIMMED_KUBERNETES_VERSION/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
        - apt-get update
        - apt-get install -y kubelet="$KUBERNETES_VERSION-*" kubeadm="$KUBERNETES_VERSION-*" kubectl="$KUBERNETES_VERSION-*" bash-completion && apt-mark hold kubelet kubectl kubeadm && systemctl enable kubelet
        - apt-get -y autoremove && apt-get -y clean all
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HCloudMachineTemplate
metadata:
  name: hetzner-mgmt-ubuntu-worker-machine
  namespace: hub-capi-system
spec:
  template:
    spec:
      type: cx23
      imageName: ubuntu-24.04
