apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-backend
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  provider:
    infisical:
      hostAPI: "http://platform-infisical-infisical-standalone-infisical.platform-security.svc:8080/api"
      secretsScope:
        projectSlug: "hub-platform"
        environmentSlug: "dev"
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-auth
            key: client-id
            namespace: platform-ops
          clientSecret:
            name: infisical-auth
            key: client-secret
            namespace: platform-ops
