apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hydra-db-credentials
  namespace: hub-platform-identity
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-backend
    kind: ClusterSecretStore
  target:
    name: hydra-db-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: hub-hydra-db-username
    - secretKey: password
      remoteRef:
        key: hub-hydra-db-password
